# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocol.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protocol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprotocol.proto\x12\x08protocol\"\"\n\x06\x61\x64\x64r_t\x12\x0b\n\x03src\x18\x01 \x01(\r\x12\x0b\n\x03\x64st\x18\x02 \x01(\r\"G\n\x05hdr_t\x12\x1e\n\x04\x61\x64\x64r\x18\x01 \x01(\x0b\x32\x10.protocol.addr_t\x12\x0b\n\x03seq\x18\x02 \x01(\r\x12\x11\n\ttimestamp\x18\x03 \x01(\r\"E\n\x05\x61\x63k_t\x12\x0f\n\x07\x61\x63k_seq\x18\x01 \x01(\r\x12+\n\x08response\x18\x02 \x01(\x0e\x32\x19.protocol.response_status\"S\n\x08packet_t\x12\x1c\n\x03hdr\x18\x01 \x01(\x0b\x32\x0f.protocol.hdr_t\x12\x1e\n\x03\x61\x63k\x18\x02 \x01(\x0b\x32\x0f.protocol.ack_tH\x00\x42\t\n\x07payload*x\n\x0fresponse_status\x12\x0f\n\x0bRESPONSE_OK\x10\x00\x12\x12\n\x0eRESPONSE_ERROR\x10\x01\x12\x11\n\rRESPONSE_NACK\x10\x02\x12\x1a\n\x16RESPONSE_NOT_SUPPORTED\x10\x03\x12\x11\n\rRESPONSE_BUSY\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESPONSE_STATUS']._serialized_start=293
  _globals['_RESPONSE_STATUS']._serialized_end=413
  _globals['_ADDR_T']._serialized_start=28
  _globals['_ADDR_T']._serialized_end=62
  _globals['_HDR_T']._serialized_start=64
  _globals['_HDR_T']._serialized_end=135
  _globals['_ACK_T']._serialized_start=137
  _globals['_ACK_T']._serialized_end=206
  _globals['_PACKET_T']._serialized_start=208
  _globals['_PACKET_T']._serialized_end=291
# @@protoc_insertion_point(module_scope)
