import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("data1.txt")

t = df["timestamp"]

plt.figure(figsize=(12, 6))
plt.plot(t, df["ukfx"], label="ukfx")
plt.plot(t, df["ukfy"], label="ukfy")
plt.plot(t, df["trilx"], label="trilx")
plt.plot(t, df["trily"], label="trily")
plt.xlabel("Timestamp")
plt.ylabel("Position")
plt.title("UKF vs Trilateration")
plt.legend()
plt.grid()
plt.show()

plt.figure(figsize=(12, 6))
plt.plot(t, df["yaw1"], label="yaw1")
plt.plot(t, df["pitch1"], label="pitch1")
plt.plot(t, df["roll1"], label="roll1")
plt.xlabel("Timestamp")
plt.ylabel("Angle")
plt.title("IMU 1 - Orientation")
plt.legend()
plt.grid()
plt.show()

plt.figure(figsize=(12, 6))
plt.plot(t, df["accx1"], label="accx1")
plt.plot(t, df["accy1"], label="accy1")
plt.plot(t, df["accz1"], label="accz1")
plt.xlabel("Timestamp")
plt.ylabel("Acceleration")
plt.title("IMU 1 - Acceleration")
plt.legend()
plt.grid()
plt.show()

plt.figure(figsize=(12, 6))
plt.plot(t, df["yaw2"], label="yaw2")
plt.plot(t, df["pitch2"], label="pitch2")
plt.plot(t, df["roll2"], label="roll2")
plt.xlabel("Timestamp")
plt.ylabel("Angle")
plt.title("IMU 2 - Orientation")
plt.legend()
plt.grid()
plt.show()

plt.figure(figsize=(12, 6))
plt.plot(t, df["accx2"], label="accx2")
plt.plot(t, df["accy2"], label="accy2")
plt.plot(t, df["accz2"], label="accz2")
plt.xlabel("Timestamp")
plt.ylabel("Acceleration")
plt.title("IMU 2 - Acceleration")
plt.legend()
plt.grid()
plt.show()