M48
; DRILL file {KiCad 9.0.7} date 2026-05-06T23:03:42+0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-06T23:03:42+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X197.4Y-85.0
X197.4Y-90.78
T2
X214.925Y-110.675
X219.175Y-110.675
T3
X194.85Y-110.1
X194.9Y-65.2
X239.772Y-109.727
X239.8Y-65.2
M30
