/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_PROTOBUF_PROTOCOL_PB_H_INCLUDED
#define PB_PROTOBUF_PROTOCOL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _protobuf_common_constant_t {
    protobuf_UNSPECIFIED = 0,
    protobuf_PROTOCOL_REV = 121
} protobuf_common_constant_t;

typedef enum _protobuf_packet_ack_response_t {
    protobuf_PACKET_ACK_RESPONSE_UNSPECIFIED = 0,
    protobuf_PACKET_ACK_RESPONSE_ACK = 1,
    protobuf_PACKET_ACK_RESPONSE_NACK_BAD_CRC = 2,
    protobuf_PACKET_ACK_RESPONSE_NACK_UNIMPLEMENTED = 3,
    protobuf_PACKET_ACK_RESPONSE_NACK_TIMED_OUT = 4,
    protobuf_PACKET_ACK_RESPONSE_NACK_BUSY = 5,
    protobuf_PACKET_ACK_RESPONSE_NACK_CMD_FAILED = 6,
    protobuf_PACKET_ACK_RESPONSE_NACK_INVALID_TYPE = 7
} protobuf_packet_ack_response_t;

typedef enum _protobuf_warning_code_t {
    protobuf_WARNING_CODE_UNSPECIFIED = 0,
    protobuf_WARNING_CODE_QUEUE_NEAR_FULL = 1,
    protobuf_WARNING_CODE_RETRYING = 2,
    protobuf_WARNING_CODE_DEGRADED_MODE = 3,
    protobuf_WARNING_CODE_PARTIAL_DATA = 4
} protobuf_warning_code_t;

typedef enum _protobuf_device_type_t {
    protobuf_DEVICE_TYPE_UNSPECIFIED = 0,
    protobuf_DEVICE_TYPE_TAG = 1,
    protobuf_DEVICE_TYPE_ANCHOR = 2,
    protobuf_DEVICE_TYPE_GATEWAY = 3,
    protobuf_DEVICE_TYPE_DEBUG_TOOL = 4
} protobuf_device_type_t;

typedef enum _protobuf_device_role_t {
    protobuf_DEVICE_ROLE_UNSPECIFIED = 0,
    protobuf_DEVICE_ROLE_TAG = 1,
    protobuf_DEVICE_ROLE_ANCHOR = 2
} protobuf_device_role_t;

typedef enum _protobuf_device_addr_t {
    protobuf_PACKET_ADDR_UNSPECIFIED = 0,
    protobuf_PACKET_ADDR_TAG = 1,
    protobuf_PACKET_ADDR_ANCHOR = 2,
    protobuf_PACKET_ADDR_CENTRAL = 3,
    protobuf_PACKET_ADDR_PERIPHERAL = 4,
    protobuf_PACKET_ADDR_HOST = 5,
    protobuf_PACKET_ADDR_DEBUG = 7,
    protobuf_PACKET_ADDR_BCAST = 15
} protobuf_device_addr_t;

typedef enum _protobuf_filter_mode_t {
    protobuf_FILTER_MODE_UNSPECIFIED = 0,
    protobuf_FILTER_MODE_KALMAN = 1
} protobuf_filter_mode_t;

typedef enum _protobuf_log_level_t {
    protobuf_LOG_LEVEL_UNSPECIFIED = 0,
    protobuf_LOG_LEVEL_ERROR = 1,
    protobuf_LOG_LEVEL_WARN = 2,
    protobuf_LOG_LEVEL_INFO = 3,
    protobuf_LOG_LEVEL_DEBUG = 4
} protobuf_log_level_t;

typedef enum _protobuf_log_type_t {
    protobuf_log_type_t_LOG_TYPE_UNSPECIFIED = 0,
    protobuf_log_type_t_LOG_TYPE_DEVICE_LOG = 1
} protobuf_log_type_t;

typedef enum _protobuf_flash_addr_region_t {
    protobuf_FLASH_ADDR_REGION_UNSPECIFIED = 0,
    protobuf_FLASH_ADDR_REGION_BOOTLOADER = 1,
    protobuf_FLASH_ADDR_REGION_APPLICATION = 2,
    protobuf_FLASH_ADDR_REGION_CONFIG = 3
} protobuf_flash_addr_region_t;

typedef enum _protobuf_ble_state_t {
    protobuf_BLE_STATE_UNSPECIFIED = 0,
    protobuf_BLE_STATE_IDLE = 1,
    protobuf_BLE_STATE_SCANNING = 2,
    protobuf_BLE_STATE_ADVERTISING = 3,
    protobuf_BLE_STATE_CONNECTING = 4,
    protobuf_BLE_STATE_CONNECTED = 5
} protobuf_ble_state_t;

typedef enum _protobuf_host_transport_t {
    protobuf_HOST_TRANSPORT_UNSPECIFIED = 0,
    protobuf_HOST_TRANSPORT_USB = 1,
    protobuf_HOST_TRANSPORT_UART = 2
} protobuf_host_transport_t;

typedef enum _protobuf_fota_state_index_t {
    protobuf_FOTA_STATE_UNSPECIFIED = 0,
    protobuf_FOTA_STATE_IDLE = 1,
    protobuf_FOTA_STATE_ERASING = 2,
    protobuf_FOTA_STATE_RECEIVING = 3,
    protobuf_FOTA_STATE_VERIFYING = 4,
    protobuf_FOTA_STATE_FINISHED = 5,
    protobuf_FOTA_STATE_ERROR = 6
} protobuf_fota_state_index_t;

/* Struct definitions */
typedef struct _protobuf_addr_t {
    protobuf_device_addr_t src;
    protobuf_device_addr_t dst;
} protobuf_addr_t;

typedef struct _protobuf_hdr_t {
    bool has_addr;
    protobuf_addr_t addr;
    uint32_t seq;
    uint32_t timestamp;
} protobuf_hdr_t;

typedef struct _protobuf_version_t {
    uint32_t major;
    uint32_t minor;
    uint32_t patch;
    uint32_t build;
    uint64_t gitsha;
} protobuf_version_t;

typedef struct _protobuf_none_t {
    uint32_t dummy;
} protobuf_none_t;

typedef struct _protobuf_ack_t {
    uint32_t ack_seq;
    protobuf_packet_ack_response_t response;
} protobuf_ack_t;

typedef struct _protobuf_device_information_get_t {
    uint32_t dummy;
} protobuf_device_information_get_t;

typedef PB_BYTES_ARRAY_T(12) protobuf_device_information_resp_t_uid_t;
typedef struct _protobuf_device_information_resp_t {
    protobuf_device_type_t device_type;
    protobuf_device_role_t role;
    bool has_fw_version;
    protobuf_version_t fw_version;
    uint32_t hw_version;
    uint32_t serial_number;
    protobuf_device_information_resp_t_uid_t uid;
} protobuf_device_information_resp_t;

typedef struct _protobuf_time_sync_get_t {
    uint32_t dummy;
} protobuf_time_sync_get_t;

typedef struct _protobuf_time_sync_set_t {
    uint64_t unix_time_ms;
    int32_t timezone_offset;
} protobuf_time_sync_set_t;

typedef struct _protobuf_time_sync_resp_t {
    uint64_t unix_time_ms;
    int32_t timezone_offset;
} protobuf_time_sync_resp_t;

typedef struct _protobuf_time_sync_adv_set_t {
    protobuf_device_type_t device_type;
    uint32_t device_id;
    uint64_t unix_time_ms;
    int32_t timezone_offset;
} protobuf_time_sync_adv_set_t;

typedef PB_BYTES_ARRAY_T(8) protobuf_uwb_cfg_t_anchor_list_t;
typedef struct _protobuf_uwb_cfg_t {
    protobuf_device_role_t role;
    uint32_t device_id;
    uint32_t ranging_period_ms;
    uint32_t rx_timeout_ms;
    uint32_t uwb_channel;
    uint32_t uwb_prf;
    uint32_t uwb_data_rate;
    uint32_t uwb_preamble_code;
    uint32_t tx_antenna_delay;
    uint32_t rx_antenna_delay;
    uint32_t tx_power;
    protobuf_uwb_cfg_t_anchor_list_t anchor_list;
} protobuf_uwb_cfg_t;

typedef struct _protobuf_sys_config_get_t {
    uint32_t dummy;
} protobuf_sys_config_get_t;

typedef struct _protobuf_sys_config_set_t {
    bool has_config;
    protobuf_uwb_cfg_t config;
} protobuf_sys_config_set_t;

typedef struct _protobuf_sys_config_resp_t {
    bool has_config;
    protobuf_uwb_cfg_t config;
} protobuf_sys_config_resp_t;

typedef struct _protobuf_sys_ranging_cfg_t {
    uint32_t rx_timeout_ms;
    uint32_t ranging_period_ms;
} protobuf_sys_ranging_cfg_t;

typedef struct _protobuf_sys_ranging_cfg_get_t {
    uint32_t dummy;
} protobuf_sys_ranging_cfg_get_t;

typedef struct _protobuf_sys_ranging_cfg_set_t {
    bool has_config;
    protobuf_sys_ranging_cfg_t config;
} protobuf_sys_ranging_cfg_set_t;

typedef struct _protobuf_sys_ranging_cfg_resp_t {
    bool has_config;
    protobuf_sys_ranging_cfg_t config;
} protobuf_sys_ranging_cfg_resp_t;

typedef struct _protobuf_ranging_start_t {
    bool reset_filter_state;
} protobuf_ranging_start_t;

typedef struct _protobuf_ranging_stop_t {
    uint32_t dummy;
} protobuf_ranging_stop_t;

typedef struct _protobuf_anchor_ranging_t {
    uint32_t anchor_id;
    uint32_t distance_mm;
    int32_t rssi_dbm;
} protobuf_anchor_ranging_t;

typedef struct _protobuf_ranging_result_t {
    float pos_x_m;
    float pos_y_m;
    float pos_z_m;
    float covariance_xx;
    float covariance_xy;
    float covariance_yy;
    float rms_error_m;
    pb_size_t anchors_count;
    protobuf_anchor_ranging_t anchors[4];
    uint32_t timestamp_ms;
} protobuf_ranging_result_t;

typedef struct _protobuf_filter_cfg_t {
    protobuf_filter_mode_t mode;
    float q_process_noise;
    float r_base;
    float innovation_alpha;
    float r_scale_min;
    float r_scale_max;
} protobuf_filter_cfg_t;

typedef struct _protobuf_filter_cfg_get_t {
    uint32_t dummy;
} protobuf_filter_cfg_get_t;

typedef struct _protobuf_filter_cfg_set_t {
    bool has_filter_cfg;
    protobuf_filter_cfg_t filter_cfg;
} protobuf_filter_cfg_set_t;

typedef struct _protobuf_filter_cfg_resp_t {
    bool has_filter_cfg;
    protobuf_filter_cfg_t filter_cfg;
} protobuf_filter_cfg_resp_t;

typedef struct _protobuf_device_reset_t {
    uint32_t dummy;
} protobuf_device_reset_t;

typedef struct _protobuf_uwb_reset_t {
    uint32_t dummy;
} protobuf_uwb_reset_t;

typedef struct _protobuf_factory_config_reset_t {
    uint32_t magic;
} protobuf_factory_config_reset_t;

typedef struct _protobuf_enter_to_bootloader_t {
    uint32_t magic; /* Special value to prevent accidental jump */
} protobuf_enter_to_bootloader_t;

typedef struct _protobuf_device_type_set_t {
    protobuf_device_type_t device_type;
} protobuf_device_type_set_t;

typedef struct _protobuf_device_type_get_t {
    uint32_t dummy;
} protobuf_device_type_get_t;

typedef struct _protobuf_flash_erase_t {
    uint32_t partition_id;
    protobuf_flash_addr_region_t flash_addr_region;
} protobuf_flash_erase_t;

typedef struct _protobuf_flash_read_t {
    uint32_t read_length;
    uint32_t address;
} protobuf_flash_read_t;

typedef PB_BYTES_ARRAY_T(200) protobuf_flash_data_t_data_t;
typedef struct _protobuf_flash_data_t {
    protobuf_flash_data_t_data_t data;
} protobuf_flash_data_t;

typedef PB_BYTES_ARRAY_T(200) protobuf_flash_write_t_data_t;
typedef struct _protobuf_flash_write_t {
    uint32_t address;
    protobuf_flash_write_t_data_t data;
} protobuf_flash_write_t;

typedef struct _protobuf_flash_verify_t {
    uint32_t dummy;
} protobuf_flash_verify_t;

/* STM32 → nRF : enable or disable BLE stack
 Useful during UWB calibration or power-saving modes. */
typedef struct _protobuf_ble_adv_config_t {
    bool enable;
    uint32_t serial_number;
    char device_name[32];
} protobuf_ble_adv_config_t;

/* STM32 → nRF : poll current BLE state
 nRF  → STM32 : response, also pushed unsolicited on state change */
typedef struct _protobuf_ble_status_get_t {
    uint32_t dummy;
} protobuf_ble_status_get_t;

typedef struct _protobuf_ble_status_resp_t {
    protobuf_ble_state_t state;
    int32_t rssi_dbm; /* valid only when connected */
    bool has_disconnect_reason;
    uint32_t disconnect_reason;
} protobuf_ble_status_resp_t;

typedef PB_BYTES_ARRAY_T(6) protobuf_ble_scan_result_t_mac_address_t;
typedef struct _protobuf_ble_scan_result_t {
    protobuf_ble_scan_result_t_mac_address_t mac_address;
    int32_t rssi_dbm;
    char name[32];
    uint32_t serial_number;
} protobuf_ble_scan_result_t;

typedef struct _protobuf_ble_conn_params_t {
    uint32_t min_interval_ms;
    uint32_t max_interval_ms;
    uint32_t slave_latency;
    uint32_t sup_timeout_ms;
} protobuf_ble_conn_params_t;

typedef struct _protobuf_ble_conn_params_get_t {
    uint32_t dummy;
} protobuf_ble_conn_params_get_t;

typedef struct _protobuf_ble_conn_params_set_t {
    bool has_params;
    protobuf_ble_conn_params_t params;
} protobuf_ble_conn_params_set_t;

typedef struct _protobuf_ble_conn_params_resp_t {
    bool has_params;
    protobuf_ble_conn_params_t params;
} protobuf_ble_conn_params_resp_t;

typedef struct _protobuf_ble_disconnect_t {
    uint32_t reason;
} protobuf_ble_disconnect_t;

typedef struct _protobuf_ble_scan_start_t {
    uint32_t duration_ms;
    uint32_t interval_ms;
    uint32_t window_ms;
    bool active_scanning;
} protobuf_ble_scan_start_t;

typedef struct _protobuf_ble_scan_stop_t {
    uint32_t dummy;
} protobuf_ble_scan_stop_t;

typedef PB_BYTES_ARRAY_T(6) protobuf_ble_connect_t_mac_address_t;
typedef struct _protobuf_ble_connect_t {
    protobuf_ble_connect_t_mac_address_t mac_address;
} protobuf_ble_connect_t;

typedef struct _protobuf_ble_adv_status_t {
    protobuf_device_type_t device;
    uint32_t device_id;
    uint32_t bat_soc_percent;
    uint32_t status_flags;
    uint32_t warning_count;
    uint32_t error_count;
    uint32_t local_timestamp_ms;
} protobuf_ble_adv_status_t;

/* Anchor distance sample
 - Produced by an anchor while connected to gateway. */
typedef struct _protobuf_anchor_distance_t {
    uint32_t anchor_id;
    uint32_t distance_mm;
    int32_t rssi_dbm;
} protobuf_anchor_distance_t;

/* Tag position sample
 - Produced by a tag while connected to gateway.
 - Position is absolute in meter unit according to current coordinate frame. */
typedef struct _protobuf_tag_position_t {
    float pos_x_m;
    float pos_y_m;
    float pos_z_m;
    float rms_error_m;
    uint32_t timestamp_ms;
} protobuf_tag_position_t;

typedef PB_BYTES_ARRAY_T(192) protobuf_log_data_t_data_t;
/* Log Data
 This is a packet used to update the data of the requested passive log
 	- Each packet will contain a finite number of log records 
 	  that can fit the transport layer packet. 
	  All records in the packet are complete and can be parsed.
	- To calculate the uploading progress, the requester needs to count 
	  the total received bytes and compare it with DATA LENGTH in LOG_RESP. */
typedef struct _protobuf_log_data_t {
    protobuf_log_type_t type;
    protobuf_log_data_t_data_t data;
} protobuf_log_data_t;

/* Acknowledge that log data has been successfully sent.
 Host sends this after receiving and processing log_data_t.
 Device then removes the corresponding segment from flash.
 offset + length identifies the exact segment to clear. */
typedef struct _protobuf_log_clear_t {
    protobuf_log_type_t type;
    uint32_t offset; /* byte offset in log storage */
    uint32_t length; /* number of bytes to clear */
} protobuf_log_clear_t;

typedef struct _protobuf_host_transport_set_t {
    protobuf_host_transport_t transport;
} protobuf_host_transport_set_t;

typedef struct _protobuf_pos_calib_cfg_t {
    bool enable_anchor_auto_calib;
    bool enable_tag_auto_calib;
    float ref_distance_xy_m;
    float tag_height_m;
    float anchor_height_m;
    uint32_t calib_anchor_id;
    uint32_t samples;
    float error_threshold_m;
    uint32_t min_delta_step;
    uint32_t max_rounds;
    float max_std_m;
} protobuf_pos_calib_cfg_t;

typedef struct _protobuf_pos_calib_cfg_get_t {
    uint32_t dummy;
} protobuf_pos_calib_cfg_get_t;

typedef struct _protobuf_pos_calib_cfg_set_t {
    bool has_config;
    protobuf_pos_calib_cfg_t config;
} protobuf_pos_calib_cfg_set_t;

typedef struct _protobuf_pos_calib_cfg_resp_t {
    bool has_config;
    protobuf_pos_calib_cfg_t config;
} protobuf_pos_calib_cfg_resp_t;

typedef struct _protobuf_anchor_layout_item_t {
    uint32_t anchor_id;
    float x_m;
    float y_m;
    float z_m;
} protobuf_anchor_layout_item_t;

typedef struct _protobuf_anchor_layout_get_t {
    uint32_t dummy;
} protobuf_anchor_layout_get_t;

typedef struct _protobuf_anchor_layout_set_t {
    pb_size_t anchors_count;
    protobuf_anchor_layout_item_t anchors[4];
} protobuf_anchor_layout_set_t;

typedef struct _protobuf_anchor_layout_resp_t {
    pb_size_t anchors_count;
    protobuf_anchor_layout_item_t anchors[4];
} protobuf_anchor_layout_resp_t;

typedef struct _protobuf_ranging_status_get_t {
    uint32_t dummy;
} protobuf_ranging_status_get_t;

typedef struct _protobuf_ranging_status_resp_t {
    uint32_t ranging_period_ms;
    uint32_t ranging_total_count;
    uint32_t ranging_success_count;
    uint32_t ranging_failed_count;
    uint32_t ranging_timeout_count;
    uint32_t last_ranging_time_ms;
    float last_rms_error_m;
    int32_t last_avg_rssi_dbm;
    uint32_t last_update_timestamp_ms;
} protobuf_ranging_status_resp_t;

typedef struct _protobuf_fota_state_resp_t {
    protobuf_fota_state_index_t state;
} protobuf_fota_state_resp_t;

typedef struct _protobuf_battery_info_resp_t {
    uint32_t bat_voltage_mv;
    uint32_t bat_soc_percent;
    int32_t remaining_min;
    bool is_charging;
} protobuf_battery_info_resp_t;

typedef struct _protobuf_battery_info_get_t {
    uint32_t dummy;
} protobuf_battery_info_get_t;

typedef struct _protobuf_packet_t {
    bool has_hdr;
    protobuf_hdr_t hdr;
    pb_size_t which_params;
    union _protobuf_packet_t_params {
        /* Core */
        protobuf_none_t none;
        protobuf_ack_t ack;
        /* Device info */
        protobuf_device_information_get_t device_information_get;
        protobuf_device_information_resp_t device_information_resp;
        /* Time sync */
        protobuf_time_sync_get_t time_sync_get;
        protobuf_time_sync_set_t time_sync_set;
        protobuf_time_sync_resp_t time_sync_resp;
        protobuf_time_sync_adv_set_t time_sync_adv_set;
        /* System config */
        protobuf_sys_config_get_t sys_config_get;
        protobuf_sys_config_set_t sys_config_set;
        protobuf_sys_config_resp_t sys_config_resp;
        /* Ranging config */
        protobuf_sys_ranging_cfg_get_t sys_ranging_cfg_get;
        protobuf_sys_ranging_cfg_set_t sys_ranging_cfg_set;
        protobuf_sys_ranging_cfg_resp_t sys_ranging_cfg_resp;
        /* Ranging control & results */
        protobuf_ranging_start_t ranging_start;
        protobuf_ranging_stop_t ranging_stop;
        protobuf_ranging_result_t ranging_result;
        protobuf_ranging_status_get_t ranging_status_get;
        protobuf_ranging_status_resp_t ranging_status_resp;
        /* Filter config */
        protobuf_filter_cfg_get_t filter_cfg_get;
        protobuf_filter_cfg_set_t filter_cfg_set;
        protobuf_filter_cfg_resp_t filter_cfg_resp;
        /* System commands */
        protobuf_device_reset_t device_reset;
        protobuf_uwb_reset_t uwb_reset;
        protobuf_factory_config_reset_t factory_config_reset;
        protobuf_device_type_set_t device_type_set;
        protobuf_device_type_get_t device_type_get;
        /* Flash */
        protobuf_flash_erase_t flash_erase;
        protobuf_flash_read_t flash_read;
        protobuf_flash_data_t flash_data;
        protobuf_flash_write_t flash_write;
        /* BLE control — STM32 ↔ nRF52832 */
        protobuf_ble_adv_config_t ble_adv_config_set;
        protobuf_ble_status_get_t ble_status_get;
        protobuf_ble_status_resp_t ble_status_resp;
        /* BLE data — STM32 → nRF52832 for broadcasting to host */
        protobuf_ble_adv_status_t ble_adv_status;
        /* Log */
        protobuf_log_data_t log_data;
        protobuf_log_clear_t log_clear;
        /* Host transport control */
        protobuf_host_transport_set_t host_transport_set;
        /* Calibration config */
        protobuf_pos_calib_cfg_get_t pos_calib_cfg_get;
        protobuf_pos_calib_cfg_set_t pos_calib_cfg_set;
        protobuf_pos_calib_cfg_resp_t pos_calib_cfg_resp;
        /* Anchor layout */
        protobuf_anchor_layout_get_t anchor_layout_get;
        protobuf_anchor_layout_set_t anchor_layout_set;
        protobuf_anchor_layout_resp_t anchor_layout_resp;
        /* FOTA Verification */
        protobuf_flash_verify_t flash_verify;
        /* BLE Central messages */
        protobuf_ble_conn_params_get_t ble_conn_params_get;
        protobuf_ble_conn_params_set_t ble_conn_params_set;
        protobuf_ble_conn_params_resp_t ble_conn_params_resp;
        protobuf_ble_disconnect_t ble_disconnect;
        protobuf_ble_scan_start_t ble_scan_start;
        protobuf_ble_scan_stop_t ble_scan_stop;
        protobuf_ble_connect_t ble_connect;
        protobuf_ble_scan_result_t ble_scan_result;
        /* Data samples */
        protobuf_anchor_distance_t anchor_distance;
        protobuf_tag_position_t tag_position;
        /* FOTA State */
        protobuf_fota_state_resp_t fota_state_resp;
        /* Battery */
        protobuf_battery_info_resp_t battery_info_resp;
        protobuf_battery_info_get_t battery_info_get;
        protobuf_enter_to_bootloader_t enter_to_bootloader;
    } params;
} protobuf_packet_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _protobuf_common_constant_t_MIN protobuf_UNSPECIFIED
#define _protobuf_common_constant_t_MAX protobuf_PROTOCOL_REV
#define _protobuf_common_constant_t_ARRAYSIZE ((protobuf_common_constant_t)(protobuf_PROTOCOL_REV+1))
#define protobuf_common_constant_t_UNSPECIFIED protobuf_UNSPECIFIED
#define protobuf_common_constant_t_PROTOCOL_REV protobuf_PROTOCOL_REV

#define _protobuf_packet_ack_response_t_MIN protobuf_PACKET_ACK_RESPONSE_UNSPECIFIED
#define _protobuf_packet_ack_response_t_MAX protobuf_PACKET_ACK_RESPONSE_NACK_INVALID_TYPE
#define _protobuf_packet_ack_response_t_ARRAYSIZE ((protobuf_packet_ack_response_t)(protobuf_PACKET_ACK_RESPONSE_NACK_INVALID_TYPE+1))
#define protobuf_packet_ack_response_t_PACKET_ACK_RESPONSE_UNSPECIFIED protobuf_PACKET_ACK_RESPONSE_UNSPECIFIED
#define protobuf_packet_ack_response_t_PACKET_ACK_RESPONSE_ACK protobuf_PACKET_ACK_RESPONSE_ACK
#define protobuf_packet_ack_response_t_PACKET_ACK_RESPONSE_NACK_BAD_CRC protobuf_PACKET_ACK_RESPONSE_NACK_BAD_CRC
#define protobuf_packet_ack_response_t_PACKET_ACK_RESPONSE_NACK_UNIMPLEMENTED protobuf_PACKET_ACK_RESPONSE_NACK_UNIMPLEMENTED
#define protobuf_packet_ack_response_t_PACKET_ACK_RESPONSE_NACK_TIMED_OUT protobuf_PACKET_ACK_RESPONSE_NACK_TIMED_OUT
#define protobuf_packet_ack_response_t_PACKET_ACK_RESPONSE_NACK_BUSY protobuf_PACKET_ACK_RESPONSE_NACK_BUSY
#define protobuf_packet_ack_response_t_PACKET_ACK_RESPONSE_NACK_CMD_FAILED protobuf_PACKET_ACK_RESPONSE_NACK_CMD_FAILED
#define protobuf_packet_ack_response_t_PACKET_ACK_RESPONSE_NACK_INVALID_TYPE protobuf_PACKET_ACK_RESPONSE_NACK_INVALID_TYPE

#define _protobuf_warning_code_t_MIN protobuf_WARNING_CODE_UNSPECIFIED
#define _protobuf_warning_code_t_MAX protobuf_WARNING_CODE_PARTIAL_DATA
#define _protobuf_warning_code_t_ARRAYSIZE ((protobuf_warning_code_t)(protobuf_WARNING_CODE_PARTIAL_DATA+1))
#define protobuf_warning_code_t_WARNING_CODE_UNSPECIFIED protobuf_WARNING_CODE_UNSPECIFIED
#define protobuf_warning_code_t_WARNING_CODE_QUEUE_NEAR_FULL protobuf_WARNING_CODE_QUEUE_NEAR_FULL
#define protobuf_warning_code_t_WARNING_CODE_RETRYING protobuf_WARNING_CODE_RETRYING
#define protobuf_warning_code_t_WARNING_CODE_DEGRADED_MODE protobuf_WARNING_CODE_DEGRADED_MODE
#define protobuf_warning_code_t_WARNING_CODE_PARTIAL_DATA protobuf_WARNING_CODE_PARTIAL_DATA

#define _protobuf_device_type_t_MIN protobuf_DEVICE_TYPE_UNSPECIFIED
#define _protobuf_device_type_t_MAX protobuf_DEVICE_TYPE_DEBUG_TOOL
#define _protobuf_device_type_t_ARRAYSIZE ((protobuf_device_type_t)(protobuf_DEVICE_TYPE_DEBUG_TOOL+1))
#define protobuf_device_type_t_DEVICE_TYPE_UNSPECIFIED protobuf_DEVICE_TYPE_UNSPECIFIED
#define protobuf_device_type_t_DEVICE_TYPE_TAG protobuf_DEVICE_TYPE_TAG
#define protobuf_device_type_t_DEVICE_TYPE_ANCHOR protobuf_DEVICE_TYPE_ANCHOR
#define protobuf_device_type_t_DEVICE_TYPE_GATEWAY protobuf_DEVICE_TYPE_GATEWAY
#define protobuf_device_type_t_DEVICE_TYPE_DEBUG_TOOL protobuf_DEVICE_TYPE_DEBUG_TOOL

#define _protobuf_device_role_t_MIN protobuf_DEVICE_ROLE_UNSPECIFIED
#define _protobuf_device_role_t_MAX protobuf_DEVICE_ROLE_ANCHOR
#define _protobuf_device_role_t_ARRAYSIZE ((protobuf_device_role_t)(protobuf_DEVICE_ROLE_ANCHOR+1))
#define protobuf_device_role_t_DEVICE_ROLE_UNSPECIFIED protobuf_DEVICE_ROLE_UNSPECIFIED
#define protobuf_device_role_t_DEVICE_ROLE_TAG protobuf_DEVICE_ROLE_TAG
#define protobuf_device_role_t_DEVICE_ROLE_ANCHOR protobuf_DEVICE_ROLE_ANCHOR

#define _protobuf_device_addr_t_MIN protobuf_PACKET_ADDR_UNSPECIFIED
#define _protobuf_device_addr_t_MAX protobuf_PACKET_ADDR_BCAST
#define _protobuf_device_addr_t_ARRAYSIZE ((protobuf_device_addr_t)(protobuf_PACKET_ADDR_BCAST+1))
#define protobuf_device_addr_t_PACKET_ADDR_UNSPECIFIED protobuf_PACKET_ADDR_UNSPECIFIED
#define protobuf_device_addr_t_PACKET_ADDR_TAG protobuf_PACKET_ADDR_TAG
#define protobuf_device_addr_t_PACKET_ADDR_ANCHOR protobuf_PACKET_ADDR_ANCHOR
#define protobuf_device_addr_t_PACKET_ADDR_CENTRAL protobuf_PACKET_ADDR_CENTRAL
#define protobuf_device_addr_t_PACKET_ADDR_PERIPHERAL protobuf_PACKET_ADDR_PERIPHERAL
#define protobuf_device_addr_t_PACKET_ADDR_HOST protobuf_PACKET_ADDR_HOST
#define protobuf_device_addr_t_PACKET_ADDR_DEBUG protobuf_PACKET_ADDR_DEBUG
#define protobuf_device_addr_t_PACKET_ADDR_BCAST protobuf_PACKET_ADDR_BCAST

#define _protobuf_filter_mode_t_MIN protobuf_FILTER_MODE_UNSPECIFIED
#define _protobuf_filter_mode_t_MAX protobuf_FILTER_MODE_KALMAN
#define _protobuf_filter_mode_t_ARRAYSIZE ((protobuf_filter_mode_t)(protobuf_FILTER_MODE_KALMAN+1))
#define protobuf_filter_mode_t_FILTER_MODE_UNSPECIFIED protobuf_FILTER_MODE_UNSPECIFIED
#define protobuf_filter_mode_t_FILTER_MODE_KALMAN protobuf_FILTER_MODE_KALMAN

#define _protobuf_log_level_t_MIN protobuf_LOG_LEVEL_UNSPECIFIED
#define _protobuf_log_level_t_MAX protobuf_LOG_LEVEL_DEBUG
#define _protobuf_log_level_t_ARRAYSIZE ((protobuf_log_level_t)(protobuf_LOG_LEVEL_DEBUG+1))
#define protobuf_log_level_t_LOG_LEVEL_UNSPECIFIED protobuf_LOG_LEVEL_UNSPECIFIED
#define protobuf_log_level_t_LOG_LEVEL_ERROR protobuf_LOG_LEVEL_ERROR
#define protobuf_log_level_t_LOG_LEVEL_WARN protobuf_LOG_LEVEL_WARN
#define protobuf_log_level_t_LOG_LEVEL_INFO protobuf_LOG_LEVEL_INFO
#define protobuf_log_level_t_LOG_LEVEL_DEBUG protobuf_LOG_LEVEL_DEBUG

#define _protobuf_log_type_t_MIN protobuf_log_type_t_LOG_TYPE_UNSPECIFIED
#define _protobuf_log_type_t_MAX protobuf_log_type_t_LOG_TYPE_DEVICE_LOG
#define _protobuf_log_type_t_ARRAYSIZE ((protobuf_log_type_t)(protobuf_log_type_t_LOG_TYPE_DEVICE_LOG+1))

#define _protobuf_flash_addr_region_t_MIN protobuf_FLASH_ADDR_REGION_UNSPECIFIED
#define _protobuf_flash_addr_region_t_MAX protobuf_FLASH_ADDR_REGION_CONFIG
#define _protobuf_flash_addr_region_t_ARRAYSIZE ((protobuf_flash_addr_region_t)(protobuf_FLASH_ADDR_REGION_CONFIG+1))
#define protobuf_flash_addr_region_t_FLASH_ADDR_REGION_UNSPECIFIED protobuf_FLASH_ADDR_REGION_UNSPECIFIED
#define protobuf_flash_addr_region_t_FLASH_ADDR_REGION_BOOTLOADER protobuf_FLASH_ADDR_REGION_BOOTLOADER
#define protobuf_flash_addr_region_t_FLASH_ADDR_REGION_APPLICATION protobuf_FLASH_ADDR_REGION_APPLICATION
#define protobuf_flash_addr_region_t_FLASH_ADDR_REGION_CONFIG protobuf_FLASH_ADDR_REGION_CONFIG

#define _protobuf_ble_state_t_MIN protobuf_BLE_STATE_UNSPECIFIED
#define _protobuf_ble_state_t_MAX protobuf_BLE_STATE_CONNECTED
#define _protobuf_ble_state_t_ARRAYSIZE ((protobuf_ble_state_t)(protobuf_BLE_STATE_CONNECTED+1))
#define protobuf_ble_state_t_BLE_STATE_UNSPECIFIED protobuf_BLE_STATE_UNSPECIFIED
#define protobuf_ble_state_t_BLE_STATE_IDLE protobuf_BLE_STATE_IDLE
#define protobuf_ble_state_t_BLE_STATE_SCANNING protobuf_BLE_STATE_SCANNING
#define protobuf_ble_state_t_BLE_STATE_ADVERTISING protobuf_BLE_STATE_ADVERTISING
#define protobuf_ble_state_t_BLE_STATE_CONNECTING protobuf_BLE_STATE_CONNECTING
#define protobuf_ble_state_t_BLE_STATE_CONNECTED protobuf_BLE_STATE_CONNECTED

#define _protobuf_host_transport_t_MIN protobuf_HOST_TRANSPORT_UNSPECIFIED
#define _protobuf_host_transport_t_MAX protobuf_HOST_TRANSPORT_UART
#define _protobuf_host_transport_t_ARRAYSIZE ((protobuf_host_transport_t)(protobuf_HOST_TRANSPORT_UART+1))
#define protobuf_host_transport_t_HOST_TRANSPORT_UNSPECIFIED protobuf_HOST_TRANSPORT_UNSPECIFIED
#define protobuf_host_transport_t_HOST_TRANSPORT_USB protobuf_HOST_TRANSPORT_USB
#define protobuf_host_transport_t_HOST_TRANSPORT_UART protobuf_HOST_TRANSPORT_UART

#define _protobuf_fota_state_index_t_MIN protobuf_FOTA_STATE_UNSPECIFIED
#define _protobuf_fota_state_index_t_MAX protobuf_FOTA_STATE_ERROR
#define _protobuf_fota_state_index_t_ARRAYSIZE ((protobuf_fota_state_index_t)(protobuf_FOTA_STATE_ERROR+1))
#define protobuf_fota_state_index_t_FOTA_STATE_UNSPECIFIED protobuf_FOTA_STATE_UNSPECIFIED
#define protobuf_fota_state_index_t_FOTA_STATE_IDLE protobuf_FOTA_STATE_IDLE
#define protobuf_fota_state_index_t_FOTA_STATE_ERASING protobuf_FOTA_STATE_ERASING
#define protobuf_fota_state_index_t_FOTA_STATE_RECEIVING protobuf_FOTA_STATE_RECEIVING
#define protobuf_fota_state_index_t_FOTA_STATE_VERIFYING protobuf_FOTA_STATE_VERIFYING
#define protobuf_fota_state_index_t_FOTA_STATE_FINISHED protobuf_FOTA_STATE_FINISHED
#define protobuf_fota_state_index_t_FOTA_STATE_ERROR protobuf_FOTA_STATE_ERROR

#define protobuf_addr_t_src_ENUMTYPE protobuf_device_addr_t
#define protobuf_addr_t_dst_ENUMTYPE protobuf_device_addr_t




#define protobuf_ack_t_response_ENUMTYPE protobuf_packet_ack_response_t


#define protobuf_device_information_resp_t_device_type_ENUMTYPE protobuf_device_type_t
#define protobuf_device_information_resp_t_role_ENUMTYPE protobuf_device_role_t




#define protobuf_time_sync_adv_set_t_device_type_ENUMTYPE protobuf_device_type_t

#define protobuf_uwb_cfg_t_role_ENUMTYPE protobuf_device_role_t












#define protobuf_filter_cfg_t_mode_ENUMTYPE protobuf_filter_mode_t








#define protobuf_device_type_set_t_device_type_ENUMTYPE protobuf_device_type_t


#define protobuf_flash_erase_t_flash_addr_region_ENUMTYPE protobuf_flash_addr_region_t







#define protobuf_ble_status_resp_t_state_ENUMTYPE protobuf_ble_state_t










#define protobuf_ble_adv_status_t_device_ENUMTYPE protobuf_device_type_t



#define protobuf_log_data_t_type_ENUMTYPE protobuf_log_type_t

#define protobuf_log_clear_t_type_ENUMTYPE protobuf_log_type_t

#define protobuf_host_transport_set_t_transport_ENUMTYPE protobuf_host_transport_t











#define protobuf_fota_state_resp_t_state_ENUMTYPE protobuf_fota_state_index_t





/* Initializer values for message structs */
#define protobuf_addr_t_init_default             {_protobuf_device_addr_t_MIN, _protobuf_device_addr_t_MIN}
#define protobuf_hdr_t_init_default              {false, protobuf_addr_t_init_default, 0, 0}
#define protobuf_version_t_init_default          {0, 0, 0, 0, 0}
#define protobuf_none_t_init_default             {0}
#define protobuf_ack_t_init_default              {0, _protobuf_packet_ack_response_t_MIN}
#define protobuf_device_information_get_t_init_default {0}
#define protobuf_device_information_resp_t_init_default {_protobuf_device_type_t_MIN, _protobuf_device_role_t_MIN, false, protobuf_version_t_init_default, 0, 0, {0, {0}}}
#define protobuf_time_sync_get_t_init_default    {0}
#define protobuf_time_sync_set_t_init_default    {0, 0}
#define protobuf_time_sync_resp_t_init_default   {0, 0}
#define protobuf_time_sync_adv_set_t_init_default {_protobuf_device_type_t_MIN, 0, 0, 0}
#define protobuf_uwb_cfg_t_init_default          {_protobuf_device_role_t_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {0, {0}}}
#define protobuf_sys_config_get_t_init_default   {0}
#define protobuf_sys_config_set_t_init_default   {false, protobuf_uwb_cfg_t_init_default}
#define protobuf_sys_config_resp_t_init_default  {false, protobuf_uwb_cfg_t_init_default}
#define protobuf_sys_ranging_cfg_t_init_default  {0, 0}
#define protobuf_sys_ranging_cfg_get_t_init_default {0}
#define protobuf_sys_ranging_cfg_set_t_init_default {false, protobuf_sys_ranging_cfg_t_init_default}
#define protobuf_sys_ranging_cfg_resp_t_init_default {false, protobuf_sys_ranging_cfg_t_init_default}
#define protobuf_ranging_start_t_init_default    {0}
#define protobuf_ranging_stop_t_init_default     {0}
#define protobuf_anchor_ranging_t_init_default   {0, 0, 0}
#define protobuf_ranging_result_t_init_default   {0, 0, 0, 0, 0, 0, 0, 0, {protobuf_anchor_ranging_t_init_default, protobuf_anchor_ranging_t_init_default, protobuf_anchor_ranging_t_init_default, protobuf_anchor_ranging_t_init_default}, 0}
#define protobuf_filter_cfg_t_init_default       {_protobuf_filter_mode_t_MIN, 0, 0, 0, 0, 0}
#define protobuf_filter_cfg_get_t_init_default   {0}
#define protobuf_filter_cfg_set_t_init_default   {false, protobuf_filter_cfg_t_init_default}
#define protobuf_filter_cfg_resp_t_init_default  {false, protobuf_filter_cfg_t_init_default}
#define protobuf_device_reset_t_init_default     {0}
#define protobuf_uwb_reset_t_init_default        {0}
#define protobuf_factory_config_reset_t_init_default {0}
#define protobuf_enter_to_bootloader_t_init_default {0}
#define protobuf_device_type_set_t_init_default  {_protobuf_device_type_t_MIN}
#define protobuf_device_type_get_t_init_default  {0}
#define protobuf_flash_erase_t_init_default      {0, _protobuf_flash_addr_region_t_MIN}
#define protobuf_flash_read_t_init_default       {0, 0}
#define protobuf_flash_data_t_init_default       {{0, {0}}}
#define protobuf_flash_write_t_init_default      {0, {0, {0}}}
#define protobuf_flash_verify_t_init_default     {0}
#define protobuf_ble_adv_config_t_init_default   {0, 0, ""}
#define protobuf_ble_status_get_t_init_default   {0}
#define protobuf_ble_status_resp_t_init_default  {_protobuf_ble_state_t_MIN, 0, false, 0}
#define protobuf_ble_scan_result_t_init_default  {{0, {0}}, 0, "", 0}
#define protobuf_ble_conn_params_t_init_default  {0, 0, 0, 0}
#define protobuf_ble_conn_params_get_t_init_default {0}
#define protobuf_ble_conn_params_set_t_init_default {false, protobuf_ble_conn_params_t_init_default}
#define protobuf_ble_conn_params_resp_t_init_default {false, protobuf_ble_conn_params_t_init_default}
#define protobuf_ble_disconnect_t_init_default   {0}
#define protobuf_ble_scan_start_t_init_default   {0, 0, 0, 0}
#define protobuf_ble_scan_stop_t_init_default    {0}
#define protobuf_ble_connect_t_init_default      {{0, {0}}}
#define protobuf_ble_adv_status_t_init_default   {_protobuf_device_type_t_MIN, 0, 0, 0, 0, 0, 0}
#define protobuf_anchor_distance_t_init_default  {0, 0, 0}
#define protobuf_tag_position_t_init_default     {0, 0, 0, 0, 0}
#define protobuf_log_data_t_init_default         {_protobuf_log_type_t_MIN, {0, {0}}}
#define protobuf_log_clear_t_init_default        {_protobuf_log_type_t_MIN, 0, 0}
#define protobuf_host_transport_set_t_init_default {_protobuf_host_transport_t_MIN}
#define protobuf_pos_calib_cfg_t_init_default    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define protobuf_pos_calib_cfg_get_t_init_default {0}
#define protobuf_pos_calib_cfg_set_t_init_default {false, protobuf_pos_calib_cfg_t_init_default}
#define protobuf_pos_calib_cfg_resp_t_init_default {false, protobuf_pos_calib_cfg_t_init_default}
#define protobuf_anchor_layout_item_t_init_default {0, 0, 0, 0}
#define protobuf_anchor_layout_get_t_init_default {0}
#define protobuf_anchor_layout_set_t_init_default {0, {protobuf_anchor_layout_item_t_init_default, protobuf_anchor_layout_item_t_init_default, protobuf_anchor_layout_item_t_init_default, protobuf_anchor_layout_item_t_init_default}}
#define protobuf_anchor_layout_resp_t_init_default {0, {protobuf_anchor_layout_item_t_init_default, protobuf_anchor_layout_item_t_init_default, protobuf_anchor_layout_item_t_init_default, protobuf_anchor_layout_item_t_init_default}}
#define protobuf_ranging_status_get_t_init_default {0}
#define protobuf_ranging_status_resp_t_init_default {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define protobuf_fota_state_resp_t_init_default  {_protobuf_fota_state_index_t_MIN}
#define protobuf_battery_info_resp_t_init_default {0, 0, 0, 0}
#define protobuf_battery_info_get_t_init_default {0}
#define protobuf_packet_t_init_default           {false, protobuf_hdr_t_init_default, 0, {protobuf_none_t_init_default}}
#define protobuf_addr_t_init_zero                {_protobuf_device_addr_t_MIN, _protobuf_device_addr_t_MIN}
#define protobuf_hdr_t_init_zero                 {false, protobuf_addr_t_init_zero, 0, 0}
#define protobuf_version_t_init_zero             {0, 0, 0, 0, 0}
#define protobuf_none_t_init_zero                {0}
#define protobuf_ack_t_init_zero                 {0, _protobuf_packet_ack_response_t_MIN}
#define protobuf_device_information_get_t_init_zero {0}
#define protobuf_device_information_resp_t_init_zero {_protobuf_device_type_t_MIN, _protobuf_device_role_t_MIN, false, protobuf_version_t_init_zero, 0, 0, {0, {0}}}
#define protobuf_time_sync_get_t_init_zero       {0}
#define protobuf_time_sync_set_t_init_zero       {0, 0}
#define protobuf_time_sync_resp_t_init_zero      {0, 0}
#define protobuf_time_sync_adv_set_t_init_zero   {_protobuf_device_type_t_MIN, 0, 0, 0}
#define protobuf_uwb_cfg_t_init_zero             {_protobuf_device_role_t_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {0, {0}}}
#define protobuf_sys_config_get_t_init_zero      {0}
#define protobuf_sys_config_set_t_init_zero      {false, protobuf_uwb_cfg_t_init_zero}
#define protobuf_sys_config_resp_t_init_zero     {false, protobuf_uwb_cfg_t_init_zero}
#define protobuf_sys_ranging_cfg_t_init_zero     {0, 0}
#define protobuf_sys_ranging_cfg_get_t_init_zero {0}
#define protobuf_sys_ranging_cfg_set_t_init_zero {false, protobuf_sys_ranging_cfg_t_init_zero}
#define protobuf_sys_ranging_cfg_resp_t_init_zero {false, protobuf_sys_ranging_cfg_t_init_zero}
#define protobuf_ranging_start_t_init_zero       {0}
#define protobuf_ranging_stop_t_init_zero        {0}
#define protobuf_anchor_ranging_t_init_zero      {0, 0, 0}
#define protobuf_ranging_result_t_init_zero      {0, 0, 0, 0, 0, 0, 0, 0, {protobuf_anchor_ranging_t_init_zero, protobuf_anchor_ranging_t_init_zero, protobuf_anchor_ranging_t_init_zero, protobuf_anchor_ranging_t_init_zero}, 0}
#define protobuf_filter_cfg_t_init_zero          {_protobuf_filter_mode_t_MIN, 0, 0, 0, 0, 0}
#define protobuf_filter_cfg_get_t_init_zero      {0}
#define protobuf_filter_cfg_set_t_init_zero      {false, protobuf_filter_cfg_t_init_zero}
#define protobuf_filter_cfg_resp_t_init_zero     {false, protobuf_filter_cfg_t_init_zero}
#define protobuf_device_reset_t_init_zero        {0}
#define protobuf_uwb_reset_t_init_zero           {0}
#define protobuf_factory_config_reset_t_init_zero {0}
#define protobuf_enter_to_bootloader_t_init_zero {0}
#define protobuf_device_type_set_t_init_zero     {_protobuf_device_type_t_MIN}
#define protobuf_device_type_get_t_init_zero     {0}
#define protobuf_flash_erase_t_init_zero         {0, _protobuf_flash_addr_region_t_MIN}
#define protobuf_flash_read_t_init_zero          {0, 0}
#define protobuf_flash_data_t_init_zero          {{0, {0}}}
#define protobuf_flash_write_t_init_zero         {0, {0, {0}}}
#define protobuf_flash_verify_t_init_zero        {0}
#define protobuf_ble_adv_config_t_init_zero      {0, 0, ""}
#define protobuf_ble_status_get_t_init_zero      {0}
#define protobuf_ble_status_resp_t_init_zero     {_protobuf_ble_state_t_MIN, 0, false, 0}
#define protobuf_ble_scan_result_t_init_zero     {{0, {0}}, 0, "", 0}
#define protobuf_ble_conn_params_t_init_zero     {0, 0, 0, 0}
#define protobuf_ble_conn_params_get_t_init_zero {0}
#define protobuf_ble_conn_params_set_t_init_zero {false, protobuf_ble_conn_params_t_init_zero}
#define protobuf_ble_conn_params_resp_t_init_zero {false, protobuf_ble_conn_params_t_init_zero}
#define protobuf_ble_disconnect_t_init_zero      {0}
#define protobuf_ble_scan_start_t_init_zero      {0, 0, 0, 0}
#define protobuf_ble_scan_stop_t_init_zero       {0}
#define protobuf_ble_connect_t_init_zero         {{0, {0}}}
#define protobuf_ble_adv_status_t_init_zero      {_protobuf_device_type_t_MIN, 0, 0, 0, 0, 0, 0}
#define protobuf_anchor_distance_t_init_zero     {0, 0, 0}
#define protobuf_tag_position_t_init_zero        {0, 0, 0, 0, 0}
#define protobuf_log_data_t_init_zero            {_protobuf_log_type_t_MIN, {0, {0}}}
#define protobuf_log_clear_t_init_zero           {_protobuf_log_type_t_MIN, 0, 0}
#define protobuf_host_transport_set_t_init_zero  {_protobuf_host_transport_t_MIN}
#define protobuf_pos_calib_cfg_t_init_zero       {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define protobuf_pos_calib_cfg_get_t_init_zero   {0}
#define protobuf_pos_calib_cfg_set_t_init_zero   {false, protobuf_pos_calib_cfg_t_init_zero}
#define protobuf_pos_calib_cfg_resp_t_init_zero  {false, protobuf_pos_calib_cfg_t_init_zero}
#define protobuf_anchor_layout_item_t_init_zero  {0, 0, 0, 0}
#define protobuf_anchor_layout_get_t_init_zero   {0}
#define protobuf_anchor_layout_set_t_init_zero   {0, {protobuf_anchor_layout_item_t_init_zero, protobuf_anchor_layout_item_t_init_zero, protobuf_anchor_layout_item_t_init_zero, protobuf_anchor_layout_item_t_init_zero}}
#define protobuf_anchor_layout_resp_t_init_zero  {0, {protobuf_anchor_layout_item_t_init_zero, protobuf_anchor_layout_item_t_init_zero, protobuf_anchor_layout_item_t_init_zero, protobuf_anchor_layout_item_t_init_zero}}
#define protobuf_ranging_status_get_t_init_zero  {0}
#define protobuf_ranging_status_resp_t_init_zero {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define protobuf_fota_state_resp_t_init_zero     {_protobuf_fota_state_index_t_MIN}
#define protobuf_battery_info_resp_t_init_zero   {0, 0, 0, 0}
#define protobuf_battery_info_get_t_init_zero    {0}
#define protobuf_packet_t_init_zero              {false, protobuf_hdr_t_init_zero, 0, {protobuf_none_t_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define protobuf_addr_t_src_tag                  1
#define protobuf_addr_t_dst_tag                  2
#define protobuf_hdr_t_addr_tag                  1
#define protobuf_hdr_t_seq_tag                   2
#define protobuf_hdr_t_timestamp_tag             3
#define protobuf_version_t_major_tag             1
#define protobuf_version_t_minor_tag             2
#define protobuf_version_t_patch_tag             3
#define protobuf_version_t_build_tag             4
#define protobuf_version_t_gitsha_tag            5
#define protobuf_none_t_dummy_tag                1
#define protobuf_ack_t_ack_seq_tag               1
#define protobuf_ack_t_response_tag              2
#define protobuf_device_information_get_t_dummy_tag 1
#define protobuf_device_information_resp_t_device_type_tag 1
#define protobuf_device_information_resp_t_role_tag 2
#define protobuf_device_information_resp_t_fw_version_tag 3
#define protobuf_device_information_resp_t_hw_version_tag 4
#define protobuf_device_information_resp_t_serial_number_tag 5
#define protobuf_device_information_resp_t_uid_tag 6
#define protobuf_time_sync_get_t_dummy_tag       1
#define protobuf_time_sync_set_t_unix_time_ms_tag 1
#define protobuf_time_sync_set_t_timezone_offset_tag 2
#define protobuf_time_sync_resp_t_unix_time_ms_tag 1
#define protobuf_time_sync_resp_t_timezone_offset_tag 2
#define protobuf_time_sync_adv_set_t_device_type_tag 1
#define protobuf_time_sync_adv_set_t_device_id_tag 2
#define protobuf_time_sync_adv_set_t_unix_time_ms_tag 3
#define protobuf_time_sync_adv_set_t_timezone_offset_tag 4
#define protobuf_uwb_cfg_t_role_tag              1
#define protobuf_uwb_cfg_t_device_id_tag         2
#define protobuf_uwb_cfg_t_ranging_period_ms_tag 3
#define protobuf_uwb_cfg_t_rx_timeout_ms_tag     4
#define protobuf_uwb_cfg_t_uwb_channel_tag       5
#define protobuf_uwb_cfg_t_uwb_prf_tag           6
#define protobuf_uwb_cfg_t_uwb_data_rate_tag     7
#define protobuf_uwb_cfg_t_uwb_preamble_code_tag 8
#define protobuf_uwb_cfg_t_tx_antenna_delay_tag  9
#define protobuf_uwb_cfg_t_rx_antenna_delay_tag  10
#define protobuf_uwb_cfg_t_tx_power_tag          11
#define protobuf_uwb_cfg_t_anchor_list_tag       12
#define protobuf_sys_config_get_t_dummy_tag      1
#define protobuf_sys_config_set_t_config_tag     1
#define protobuf_sys_config_resp_t_config_tag    1
#define protobuf_sys_ranging_cfg_t_rx_timeout_ms_tag 1
#define protobuf_sys_ranging_cfg_t_ranging_period_ms_tag 2
#define protobuf_sys_ranging_cfg_get_t_dummy_tag 1
#define protobuf_sys_ranging_cfg_set_t_config_tag 1
#define protobuf_sys_ranging_cfg_resp_t_config_tag 1
#define protobuf_ranging_start_t_reset_filter_state_tag 1
#define protobuf_ranging_stop_t_dummy_tag        1
#define protobuf_anchor_ranging_t_anchor_id_tag  1
#define protobuf_anchor_ranging_t_distance_mm_tag 2
#define protobuf_anchor_ranging_t_rssi_dbm_tag   3
#define protobuf_ranging_result_t_pos_x_m_tag    1
#define protobuf_ranging_result_t_pos_y_m_tag    2
#define protobuf_ranging_result_t_pos_z_m_tag    3
#define protobuf_ranging_result_t_covariance_xx_tag 4
#define protobuf_ranging_result_t_covariance_xy_tag 5
#define protobuf_ranging_result_t_covariance_yy_tag 6
#define protobuf_ranging_result_t_rms_error_m_tag 7
#define protobuf_ranging_result_t_anchors_tag    8
#define protobuf_ranging_result_t_timestamp_ms_tag 9
#define protobuf_filter_cfg_t_mode_tag           1
#define protobuf_filter_cfg_t_q_process_noise_tag 2
#define protobuf_filter_cfg_t_r_base_tag         3
#define protobuf_filter_cfg_t_innovation_alpha_tag 4
#define protobuf_filter_cfg_t_r_scale_min_tag    5
#define protobuf_filter_cfg_t_r_scale_max_tag    6
#define protobuf_filter_cfg_get_t_dummy_tag      1
#define protobuf_filter_cfg_set_t_filter_cfg_tag 1
#define protobuf_filter_cfg_resp_t_filter_cfg_tag 1
#define protobuf_device_reset_t_dummy_tag        1
#define protobuf_uwb_reset_t_dummy_tag           1
#define protobuf_factory_config_reset_t_magic_tag 1
#define protobuf_enter_to_bootloader_t_magic_tag 1
#define protobuf_device_type_set_t_device_type_tag 1
#define protobuf_device_type_get_t_dummy_tag     1
#define protobuf_flash_erase_t_partition_id_tag  1
#define protobuf_flash_erase_t_flash_addr_region_tag 2
#define protobuf_flash_read_t_read_length_tag    1
#define protobuf_flash_read_t_address_tag        2
#define protobuf_flash_data_t_data_tag           1
#define protobuf_flash_write_t_address_tag       1
#define protobuf_flash_write_t_data_tag          2
#define protobuf_flash_verify_t_dummy_tag        1
#define protobuf_ble_adv_config_t_enable_tag     1
#define protobuf_ble_adv_config_t_serial_number_tag 2
#define protobuf_ble_adv_config_t_device_name_tag 3
#define protobuf_ble_status_get_t_dummy_tag      1
#define protobuf_ble_status_resp_t_state_tag     1
#define protobuf_ble_status_resp_t_rssi_dbm_tag  2
#define protobuf_ble_status_resp_t_disconnect_reason_tag 3
#define protobuf_ble_scan_result_t_mac_address_tag 1
#define protobuf_ble_scan_result_t_rssi_dbm_tag  2
#define protobuf_ble_scan_result_t_name_tag      3
#define protobuf_ble_scan_result_t_serial_number_tag 4
#define protobuf_ble_conn_params_t_min_interval_ms_tag 1
#define protobuf_ble_conn_params_t_max_interval_ms_tag 2
#define protobuf_ble_conn_params_t_slave_latency_tag 3
#define protobuf_ble_conn_params_t_sup_timeout_ms_tag 4
#define protobuf_ble_conn_params_get_t_dummy_tag 1
#define protobuf_ble_conn_params_set_t_params_tag 1
#define protobuf_ble_conn_params_resp_t_params_tag 1
#define protobuf_ble_disconnect_t_reason_tag     1
#define protobuf_ble_scan_start_t_duration_ms_tag 1
#define protobuf_ble_scan_start_t_interval_ms_tag 2
#define protobuf_ble_scan_start_t_window_ms_tag  3
#define protobuf_ble_scan_start_t_active_scanning_tag 4
#define protobuf_ble_scan_stop_t_dummy_tag       1
#define protobuf_ble_connect_t_mac_address_tag   1
#define protobuf_ble_adv_status_t_device_tag     1
#define protobuf_ble_adv_status_t_device_id_tag  2
#define protobuf_ble_adv_status_t_bat_soc_percent_tag 3
#define protobuf_ble_adv_status_t_status_flags_tag 4
#define protobuf_ble_adv_status_t_warning_count_tag 5
#define protobuf_ble_adv_status_t_error_count_tag 6
#define protobuf_ble_adv_status_t_local_timestamp_ms_tag 7
#define protobuf_anchor_distance_t_anchor_id_tag 1
#define protobuf_anchor_distance_t_distance_mm_tag 2
#define protobuf_anchor_distance_t_rssi_dbm_tag  3
#define protobuf_tag_position_t_pos_x_m_tag      1
#define protobuf_tag_position_t_pos_y_m_tag      2
#define protobuf_tag_position_t_pos_z_m_tag      3
#define protobuf_tag_position_t_rms_error_m_tag  4
#define protobuf_tag_position_t_timestamp_ms_tag 5
#define protobuf_log_data_t_type_tag             1
#define protobuf_log_data_t_data_tag             2
#define protobuf_log_clear_t_type_tag            1
#define protobuf_log_clear_t_offset_tag          2
#define protobuf_log_clear_t_length_tag          3
#define protobuf_host_transport_set_t_transport_tag 1
#define protobuf_pos_calib_cfg_t_enable_anchor_auto_calib_tag 1
#define protobuf_pos_calib_cfg_t_enable_tag_auto_calib_tag 2
#define protobuf_pos_calib_cfg_t_ref_distance_xy_m_tag 3
#define protobuf_pos_calib_cfg_t_tag_height_m_tag 4
#define protobuf_pos_calib_cfg_t_anchor_height_m_tag 5
#define protobuf_pos_calib_cfg_t_calib_anchor_id_tag 6
#define protobuf_pos_calib_cfg_t_samples_tag     7
#define protobuf_pos_calib_cfg_t_error_threshold_m_tag 8
#define protobuf_pos_calib_cfg_t_min_delta_step_tag 9
#define protobuf_pos_calib_cfg_t_max_rounds_tag  10
#define protobuf_pos_calib_cfg_t_max_std_m_tag   11
#define protobuf_pos_calib_cfg_get_t_dummy_tag   1
#define protobuf_pos_calib_cfg_set_t_config_tag  1
#define protobuf_pos_calib_cfg_resp_t_config_tag 1
#define protobuf_anchor_layout_item_t_anchor_id_tag 1
#define protobuf_anchor_layout_item_t_x_m_tag    2
#define protobuf_anchor_layout_item_t_y_m_tag    3
#define protobuf_anchor_layout_item_t_z_m_tag    4
#define protobuf_anchor_layout_get_t_dummy_tag   1
#define protobuf_anchor_layout_set_t_anchors_tag 1
#define protobuf_anchor_layout_resp_t_anchors_tag 1
#define protobuf_ranging_status_get_t_dummy_tag  1
#define protobuf_ranging_status_resp_t_ranging_period_ms_tag 1
#define protobuf_ranging_status_resp_t_ranging_total_count_tag 2
#define protobuf_ranging_status_resp_t_ranging_success_count_tag 3
#define protobuf_ranging_status_resp_t_ranging_failed_count_tag 4
#define protobuf_ranging_status_resp_t_ranging_timeout_count_tag 5
#define protobuf_ranging_status_resp_t_last_ranging_time_ms_tag 6
#define protobuf_ranging_status_resp_t_last_rms_error_m_tag 7
#define protobuf_ranging_status_resp_t_last_avg_rssi_dbm_tag 8
#define protobuf_ranging_status_resp_t_last_update_timestamp_ms_tag 9
#define protobuf_fota_state_resp_t_state_tag     1
#define protobuf_battery_info_resp_t_bat_voltage_mv_tag 1
#define protobuf_battery_info_resp_t_bat_soc_percent_tag 2
#define protobuf_battery_info_resp_t_remaining_min_tag 3
#define protobuf_battery_info_resp_t_is_charging_tag 4
#define protobuf_battery_info_get_t_dummy_tag    1
#define protobuf_packet_t_hdr_tag                1
#define protobuf_packet_t_none_tag               2
#define protobuf_packet_t_ack_tag                3
#define protobuf_packet_t_device_information_get_tag 4
#define protobuf_packet_t_device_information_resp_tag 5
#define protobuf_packet_t_time_sync_get_tag      6
#define protobuf_packet_t_time_sync_set_tag      7
#define protobuf_packet_t_time_sync_resp_tag     8
#define protobuf_packet_t_time_sync_adv_set_tag  9
#define protobuf_packet_t_sys_config_get_tag     10
#define protobuf_packet_t_sys_config_set_tag     11
#define protobuf_packet_t_sys_config_resp_tag    12
#define protobuf_packet_t_sys_ranging_cfg_get_tag 13
#define protobuf_packet_t_sys_ranging_cfg_set_tag 14
#define protobuf_packet_t_sys_ranging_cfg_resp_tag 15
#define protobuf_packet_t_ranging_start_tag      16
#define protobuf_packet_t_ranging_stop_tag       17
#define protobuf_packet_t_ranging_result_tag     18
#define protobuf_packet_t_ranging_status_get_tag 19
#define protobuf_packet_t_ranging_status_resp_tag 20
#define protobuf_packet_t_filter_cfg_get_tag     21
#define protobuf_packet_t_filter_cfg_set_tag     22
#define protobuf_packet_t_filter_cfg_resp_tag    23
#define protobuf_packet_t_device_reset_tag       24
#define protobuf_packet_t_uwb_reset_tag          25
#define protobuf_packet_t_factory_config_reset_tag 26
#define protobuf_packet_t_device_type_set_tag    27
#define protobuf_packet_t_device_type_get_tag    28
#define protobuf_packet_t_flash_erase_tag        29
#define protobuf_packet_t_flash_read_tag         30
#define protobuf_packet_t_flash_data_tag         31
#define protobuf_packet_t_flash_write_tag        32
#define protobuf_packet_t_ble_adv_config_set_tag 33
#define protobuf_packet_t_ble_status_get_tag     34
#define protobuf_packet_t_ble_status_resp_tag    35
#define protobuf_packet_t_ble_adv_status_tag     36
#define protobuf_packet_t_log_data_tag           37
#define protobuf_packet_t_log_clear_tag          38
#define protobuf_packet_t_host_transport_set_tag 39
#define protobuf_packet_t_pos_calib_cfg_get_tag  40
#define protobuf_packet_t_pos_calib_cfg_set_tag  41
#define protobuf_packet_t_pos_calib_cfg_resp_tag 42
#define protobuf_packet_t_anchor_layout_get_tag  43
#define protobuf_packet_t_anchor_layout_set_tag  44
#define protobuf_packet_t_anchor_layout_resp_tag 45
#define protobuf_packet_t_flash_verify_tag       46
#define protobuf_packet_t_ble_conn_params_get_tag 47
#define protobuf_packet_t_ble_conn_params_set_tag 48
#define protobuf_packet_t_ble_conn_params_resp_tag 49
#define protobuf_packet_t_ble_disconnect_tag     50
#define protobuf_packet_t_ble_scan_start_tag     51
#define protobuf_packet_t_ble_scan_stop_tag      52
#define protobuf_packet_t_ble_connect_tag        53
#define protobuf_packet_t_ble_scan_result_tag    54
#define protobuf_packet_t_anchor_distance_tag    55
#define protobuf_packet_t_tag_position_tag       56
#define protobuf_packet_t_fota_state_resp_tag    57
#define protobuf_packet_t_battery_info_resp_tag  60
#define protobuf_packet_t_battery_info_get_tag   61
#define protobuf_packet_t_enter_to_bootloader_tag 62

/* Struct field encoding specification for nanopb */
#define protobuf_addr_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    src,               1) \
X(a, STATIC,   SINGULAR, UENUM,    dst,               2)
#define protobuf_addr_t_CALLBACK NULL
#define protobuf_addr_t_DEFAULT NULL

#define protobuf_hdr_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  addr,              1) \
X(a, STATIC,   SINGULAR, UINT32,   seq,               2) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         3)
#define protobuf_hdr_t_CALLBACK NULL
#define protobuf_hdr_t_DEFAULT NULL
#define protobuf_hdr_t_addr_MSGTYPE protobuf_addr_t

#define protobuf_version_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   major,             1) \
X(a, STATIC,   SINGULAR, UINT32,   minor,             2) \
X(a, STATIC,   SINGULAR, UINT32,   patch,             3) \
X(a, STATIC,   SINGULAR, UINT32,   build,             4) \
X(a, STATIC,   SINGULAR, UINT64,   gitsha,            5)
#define protobuf_version_t_CALLBACK NULL
#define protobuf_version_t_DEFAULT NULL

#define protobuf_none_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_none_t_CALLBACK NULL
#define protobuf_none_t_DEFAULT NULL

#define protobuf_ack_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ack_seq,           1) \
X(a, STATIC,   SINGULAR, UENUM,    response,          2)
#define protobuf_ack_t_CALLBACK NULL
#define protobuf_ack_t_DEFAULT NULL

#define protobuf_device_information_get_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_device_information_get_t_CALLBACK NULL
#define protobuf_device_information_get_t_DEFAULT NULL

#define protobuf_device_information_resp_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    device_type,       1) \
X(a, STATIC,   SINGULAR, UENUM,    role,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  fw_version,        3) \
X(a, STATIC,   SINGULAR, UINT32,   hw_version,        4) \
X(a, STATIC,   SINGULAR, UINT32,   serial_number,     5) \
X(a, STATIC,   SINGULAR, BYTES,    uid,               6)
#define protobuf_device_information_resp_t_CALLBACK NULL
#define protobuf_device_information_resp_t_DEFAULT NULL
#define protobuf_device_information_resp_t_fw_version_MSGTYPE protobuf_version_t

#define protobuf_time_sync_get_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_time_sync_get_t_CALLBACK NULL
#define protobuf_time_sync_get_t_DEFAULT NULL

#define protobuf_time_sync_set_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   unix_time_ms,      1) \
X(a, STATIC,   SINGULAR, INT32,    timezone_offset,   2)
#define protobuf_time_sync_set_t_CALLBACK NULL
#define protobuf_time_sync_set_t_DEFAULT NULL

#define protobuf_time_sync_resp_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   unix_time_ms,      1) \
X(a, STATIC,   SINGULAR, INT32,    timezone_offset,   2)
#define protobuf_time_sync_resp_t_CALLBACK NULL
#define protobuf_time_sync_resp_t_DEFAULT NULL

#define protobuf_time_sync_adv_set_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    device_type,       1) \
X(a, STATIC,   SINGULAR, UINT32,   device_id,         2) \
X(a, STATIC,   SINGULAR, UINT64,   unix_time_ms,      3) \
X(a, STATIC,   SINGULAR, INT32,    timezone_offset,   4)
#define protobuf_time_sync_adv_set_t_CALLBACK NULL
#define protobuf_time_sync_adv_set_t_DEFAULT NULL

#define protobuf_uwb_cfg_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    role,              1) \
X(a, STATIC,   SINGULAR, UINT32,   device_id,         2) \
X(a, STATIC,   SINGULAR, UINT32,   ranging_period_ms,   3) \
X(a, STATIC,   SINGULAR, UINT32,   rx_timeout_ms,     4) \
X(a, STATIC,   SINGULAR, UINT32,   uwb_channel,       5) \
X(a, STATIC,   SINGULAR, UINT32,   uwb_prf,           6) \
X(a, STATIC,   SINGULAR, UINT32,   uwb_data_rate,     7) \
X(a, STATIC,   SINGULAR, UINT32,   uwb_preamble_code,   8) \
X(a, STATIC,   SINGULAR, UINT32,   tx_antenna_delay,   9) \
X(a, STATIC,   SINGULAR, UINT32,   rx_antenna_delay,  10) \
X(a, STATIC,   SINGULAR, UINT32,   tx_power,         11) \
X(a, STATIC,   SINGULAR, BYTES,    anchor_list,      12)
#define protobuf_uwb_cfg_t_CALLBACK NULL
#define protobuf_uwb_cfg_t_DEFAULT NULL

#define protobuf_sys_config_get_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_sys_config_get_t_CALLBACK NULL
#define protobuf_sys_config_get_t_DEFAULT NULL

#define protobuf_sys_config_set_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  config,            1)
#define protobuf_sys_config_set_t_CALLBACK NULL
#define protobuf_sys_config_set_t_DEFAULT NULL
#define protobuf_sys_config_set_t_config_MSGTYPE protobuf_uwb_cfg_t

#define protobuf_sys_config_resp_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  config,            1)
#define protobuf_sys_config_resp_t_CALLBACK NULL
#define protobuf_sys_config_resp_t_DEFAULT NULL
#define protobuf_sys_config_resp_t_config_MSGTYPE protobuf_uwb_cfg_t

#define protobuf_sys_ranging_cfg_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   rx_timeout_ms,     1) \
X(a, STATIC,   SINGULAR, UINT32,   ranging_period_ms,   2)
#define protobuf_sys_ranging_cfg_t_CALLBACK NULL
#define protobuf_sys_ranging_cfg_t_DEFAULT NULL

#define protobuf_sys_ranging_cfg_get_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_sys_ranging_cfg_get_t_CALLBACK NULL
#define protobuf_sys_ranging_cfg_get_t_DEFAULT NULL

#define protobuf_sys_ranging_cfg_set_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  config,            1)
#define protobuf_sys_ranging_cfg_set_t_CALLBACK NULL
#define protobuf_sys_ranging_cfg_set_t_DEFAULT NULL
#define protobuf_sys_ranging_cfg_set_t_config_MSGTYPE protobuf_sys_ranging_cfg_t

#define protobuf_sys_ranging_cfg_resp_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  config,            1)
#define protobuf_sys_ranging_cfg_resp_t_CALLBACK NULL
#define protobuf_sys_ranging_cfg_resp_t_DEFAULT NULL
#define protobuf_sys_ranging_cfg_resp_t_config_MSGTYPE protobuf_sys_ranging_cfg_t

#define protobuf_ranging_start_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     reset_filter_state,   1)
#define protobuf_ranging_start_t_CALLBACK NULL
#define protobuf_ranging_start_t_DEFAULT NULL

#define protobuf_ranging_stop_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_ranging_stop_t_CALLBACK NULL
#define protobuf_ranging_stop_t_DEFAULT NULL

#define protobuf_anchor_ranging_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   anchor_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   distance_mm,       2) \
X(a, STATIC,   SINGULAR, INT32,    rssi_dbm,          3)
#define protobuf_anchor_ranging_t_CALLBACK NULL
#define protobuf_anchor_ranging_t_DEFAULT NULL

#define protobuf_ranging_result_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    pos_x_m,           1) \
X(a, STATIC,   SINGULAR, FLOAT,    pos_y_m,           2) \
X(a, STATIC,   SINGULAR, FLOAT,    pos_z_m,           3) \
X(a, STATIC,   SINGULAR, FLOAT,    covariance_xx,     4) \
X(a, STATIC,   SINGULAR, FLOAT,    covariance_xy,     5) \
X(a, STATIC,   SINGULAR, FLOAT,    covariance_yy,     6) \
X(a, STATIC,   SINGULAR, FLOAT,    rms_error_m,       7) \
X(a, STATIC,   REPEATED, MESSAGE,  anchors,           8) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_ms,      9)
#define protobuf_ranging_result_t_CALLBACK NULL
#define protobuf_ranging_result_t_DEFAULT NULL
#define protobuf_ranging_result_t_anchors_MSGTYPE protobuf_anchor_ranging_t

#define protobuf_filter_cfg_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    q_process_noise,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    r_base,            3) \
X(a, STATIC,   SINGULAR, FLOAT,    innovation_alpha,   4) \
X(a, STATIC,   SINGULAR, FLOAT,    r_scale_min,       5) \
X(a, STATIC,   SINGULAR, FLOAT,    r_scale_max,       6)
#define protobuf_filter_cfg_t_CALLBACK NULL
#define protobuf_filter_cfg_t_DEFAULT NULL

#define protobuf_filter_cfg_get_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_filter_cfg_get_t_CALLBACK NULL
#define protobuf_filter_cfg_get_t_DEFAULT NULL

#define protobuf_filter_cfg_set_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  filter_cfg,        1)
#define protobuf_filter_cfg_set_t_CALLBACK NULL
#define protobuf_filter_cfg_set_t_DEFAULT NULL
#define protobuf_filter_cfg_set_t_filter_cfg_MSGTYPE protobuf_filter_cfg_t

#define protobuf_filter_cfg_resp_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  filter_cfg,        1)
#define protobuf_filter_cfg_resp_t_CALLBACK NULL
#define protobuf_filter_cfg_resp_t_DEFAULT NULL
#define protobuf_filter_cfg_resp_t_filter_cfg_MSGTYPE protobuf_filter_cfg_t

#define protobuf_device_reset_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_device_reset_t_CALLBACK NULL
#define protobuf_device_reset_t_DEFAULT NULL

#define protobuf_uwb_reset_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_uwb_reset_t_CALLBACK NULL
#define protobuf_uwb_reset_t_DEFAULT NULL

#define protobuf_factory_config_reset_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   magic,             1)
#define protobuf_factory_config_reset_t_CALLBACK NULL
#define protobuf_factory_config_reset_t_DEFAULT NULL

#define protobuf_enter_to_bootloader_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   magic,             1)
#define protobuf_enter_to_bootloader_t_CALLBACK NULL
#define protobuf_enter_to_bootloader_t_DEFAULT NULL

#define protobuf_device_type_set_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    device_type,       1)
#define protobuf_device_type_set_t_CALLBACK NULL
#define protobuf_device_type_set_t_DEFAULT NULL

#define protobuf_device_type_get_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_device_type_get_t_CALLBACK NULL
#define protobuf_device_type_get_t_DEFAULT NULL

#define protobuf_flash_erase_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   partition_id,      1) \
X(a, STATIC,   SINGULAR, UENUM,    flash_addr_region,   2)
#define protobuf_flash_erase_t_CALLBACK NULL
#define protobuf_flash_erase_t_DEFAULT NULL

#define protobuf_flash_read_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   read_length,       1) \
X(a, STATIC,   SINGULAR, UINT32,   address,           2)
#define protobuf_flash_read_t_CALLBACK NULL
#define protobuf_flash_read_t_DEFAULT NULL

#define protobuf_flash_data_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    data,              1)
#define protobuf_flash_data_t_CALLBACK NULL
#define protobuf_flash_data_t_DEFAULT NULL

#define protobuf_flash_write_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   address,           1) \
X(a, STATIC,   SINGULAR, BYTES,    data,              2)
#define protobuf_flash_write_t_CALLBACK NULL
#define protobuf_flash_write_t_DEFAULT NULL

#define protobuf_flash_verify_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_flash_verify_t_CALLBACK NULL
#define protobuf_flash_verify_t_DEFAULT NULL

#define protobuf_ble_adv_config_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enable,            1) \
X(a, STATIC,   SINGULAR, UINT32,   serial_number,     2) \
X(a, STATIC,   SINGULAR, STRING,   device_name,       3)
#define protobuf_ble_adv_config_t_CALLBACK NULL
#define protobuf_ble_adv_config_t_DEFAULT NULL

#define protobuf_ble_status_get_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_ble_status_get_t_CALLBACK NULL
#define protobuf_ble_status_get_t_DEFAULT NULL

#define protobuf_ble_status_resp_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    state,             1) \
X(a, STATIC,   SINGULAR, INT32,    rssi_dbm,          2) \
X(a, STATIC,   OPTIONAL, UINT32,   disconnect_reason,   3)
#define protobuf_ble_status_resp_t_CALLBACK NULL
#define protobuf_ble_status_resp_t_DEFAULT NULL

#define protobuf_ble_scan_result_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    mac_address,       1) \
X(a, STATIC,   SINGULAR, INT32,    rssi_dbm,          2) \
X(a, STATIC,   SINGULAR, STRING,   name,              3) \
X(a, STATIC,   SINGULAR, UINT32,   serial_number,     4)
#define protobuf_ble_scan_result_t_CALLBACK NULL
#define protobuf_ble_scan_result_t_DEFAULT NULL

#define protobuf_ble_conn_params_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   min_interval_ms,   1) \
X(a, STATIC,   SINGULAR, UINT32,   max_interval_ms,   2) \
X(a, STATIC,   SINGULAR, UINT32,   slave_latency,     3) \
X(a, STATIC,   SINGULAR, UINT32,   sup_timeout_ms,    4)
#define protobuf_ble_conn_params_t_CALLBACK NULL
#define protobuf_ble_conn_params_t_DEFAULT NULL

#define protobuf_ble_conn_params_get_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_ble_conn_params_get_t_CALLBACK NULL
#define protobuf_ble_conn_params_get_t_DEFAULT NULL

#define protobuf_ble_conn_params_set_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  params,            1)
#define protobuf_ble_conn_params_set_t_CALLBACK NULL
#define protobuf_ble_conn_params_set_t_DEFAULT NULL
#define protobuf_ble_conn_params_set_t_params_MSGTYPE protobuf_ble_conn_params_t

#define protobuf_ble_conn_params_resp_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  params,            1)
#define protobuf_ble_conn_params_resp_t_CALLBACK NULL
#define protobuf_ble_conn_params_resp_t_DEFAULT NULL
#define protobuf_ble_conn_params_resp_t_params_MSGTYPE protobuf_ble_conn_params_t

#define protobuf_ble_disconnect_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   reason,            1)
#define protobuf_ble_disconnect_t_CALLBACK NULL
#define protobuf_ble_disconnect_t_DEFAULT NULL

#define protobuf_ble_scan_start_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   duration_ms,       1) \
X(a, STATIC,   SINGULAR, UINT32,   interval_ms,       2) \
X(a, STATIC,   SINGULAR, UINT32,   window_ms,         3) \
X(a, STATIC,   SINGULAR, BOOL,     active_scanning,   4)
#define protobuf_ble_scan_start_t_CALLBACK NULL
#define protobuf_ble_scan_start_t_DEFAULT NULL

#define protobuf_ble_scan_stop_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_ble_scan_stop_t_CALLBACK NULL
#define protobuf_ble_scan_stop_t_DEFAULT NULL

#define protobuf_ble_connect_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    mac_address,       1)
#define protobuf_ble_connect_t_CALLBACK NULL
#define protobuf_ble_connect_t_DEFAULT NULL

#define protobuf_ble_adv_status_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    device,            1) \
X(a, STATIC,   SINGULAR, UINT32,   device_id,         2) \
X(a, STATIC,   SINGULAR, UINT32,   bat_soc_percent,   3) \
X(a, STATIC,   SINGULAR, UINT32,   status_flags,      4) \
X(a, STATIC,   SINGULAR, UINT32,   warning_count,     5) \
X(a, STATIC,   SINGULAR, UINT32,   error_count,       6) \
X(a, STATIC,   SINGULAR, UINT32,   local_timestamp_ms,   7)
#define protobuf_ble_adv_status_t_CALLBACK NULL
#define protobuf_ble_adv_status_t_DEFAULT NULL

#define protobuf_anchor_distance_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   anchor_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   distance_mm,       2) \
X(a, STATIC,   SINGULAR, INT32,    rssi_dbm,          3)
#define protobuf_anchor_distance_t_CALLBACK NULL
#define protobuf_anchor_distance_t_DEFAULT NULL

#define protobuf_tag_position_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    pos_x_m,           1) \
X(a, STATIC,   SINGULAR, FLOAT,    pos_y_m,           2) \
X(a, STATIC,   SINGULAR, FLOAT,    pos_z_m,           3) \
X(a, STATIC,   SINGULAR, FLOAT,    rms_error_m,       4) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_ms,      5)
#define protobuf_tag_position_t_CALLBACK NULL
#define protobuf_tag_position_t_DEFAULT NULL

#define protobuf_log_data_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, BYTES,    data,              2)
#define protobuf_log_data_t_CALLBACK NULL
#define protobuf_log_data_t_DEFAULT NULL

#define protobuf_log_clear_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            2) \
X(a, STATIC,   SINGULAR, UINT32,   length,            3)
#define protobuf_log_clear_t_CALLBACK NULL
#define protobuf_log_clear_t_DEFAULT NULL

#define protobuf_host_transport_set_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    transport,         1)
#define protobuf_host_transport_set_t_CALLBACK NULL
#define protobuf_host_transport_set_t_DEFAULT NULL

#define protobuf_pos_calib_cfg_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enable_anchor_auto_calib,   1) \
X(a, STATIC,   SINGULAR, BOOL,     enable_tag_auto_calib,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    ref_distance_xy_m,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    tag_height_m,      4) \
X(a, STATIC,   SINGULAR, FLOAT,    anchor_height_m,   5) \
X(a, STATIC,   SINGULAR, UINT32,   calib_anchor_id,   6) \
X(a, STATIC,   SINGULAR, UINT32,   samples,           7) \
X(a, STATIC,   SINGULAR, FLOAT,    error_threshold_m,   8) \
X(a, STATIC,   SINGULAR, UINT32,   min_delta_step,    9) \
X(a, STATIC,   SINGULAR, UINT32,   max_rounds,       10) \
X(a, STATIC,   SINGULAR, FLOAT,    max_std_m,        11)
#define protobuf_pos_calib_cfg_t_CALLBACK NULL
#define protobuf_pos_calib_cfg_t_DEFAULT NULL

#define protobuf_pos_calib_cfg_get_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_pos_calib_cfg_get_t_CALLBACK NULL
#define protobuf_pos_calib_cfg_get_t_DEFAULT NULL

#define protobuf_pos_calib_cfg_set_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  config,            1)
#define protobuf_pos_calib_cfg_set_t_CALLBACK NULL
#define protobuf_pos_calib_cfg_set_t_DEFAULT NULL
#define protobuf_pos_calib_cfg_set_t_config_MSGTYPE protobuf_pos_calib_cfg_t

#define protobuf_pos_calib_cfg_resp_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  config,            1)
#define protobuf_pos_calib_cfg_resp_t_CALLBACK NULL
#define protobuf_pos_calib_cfg_resp_t_DEFAULT NULL
#define protobuf_pos_calib_cfg_resp_t_config_MSGTYPE protobuf_pos_calib_cfg_t

#define protobuf_anchor_layout_item_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   anchor_id,         1) \
X(a, STATIC,   SINGULAR, FLOAT,    x_m,               2) \
X(a, STATIC,   SINGULAR, FLOAT,    y_m,               3) \
X(a, STATIC,   SINGULAR, FLOAT,    z_m,               4)
#define protobuf_anchor_layout_item_t_CALLBACK NULL
#define protobuf_anchor_layout_item_t_DEFAULT NULL

#define protobuf_anchor_layout_get_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_anchor_layout_get_t_CALLBACK NULL
#define protobuf_anchor_layout_get_t_DEFAULT NULL

#define protobuf_anchor_layout_set_t_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  anchors,           1)
#define protobuf_anchor_layout_set_t_CALLBACK NULL
#define protobuf_anchor_layout_set_t_DEFAULT NULL
#define protobuf_anchor_layout_set_t_anchors_MSGTYPE protobuf_anchor_layout_item_t

#define protobuf_anchor_layout_resp_t_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  anchors,           1)
#define protobuf_anchor_layout_resp_t_CALLBACK NULL
#define protobuf_anchor_layout_resp_t_DEFAULT NULL
#define protobuf_anchor_layout_resp_t_anchors_MSGTYPE protobuf_anchor_layout_item_t

#define protobuf_ranging_status_get_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_ranging_status_get_t_CALLBACK NULL
#define protobuf_ranging_status_get_t_DEFAULT NULL

#define protobuf_ranging_status_resp_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ranging_period_ms,   1) \
X(a, STATIC,   SINGULAR, UINT32,   ranging_total_count,   2) \
X(a, STATIC,   SINGULAR, UINT32,   ranging_success_count,   3) \
X(a, STATIC,   SINGULAR, UINT32,   ranging_failed_count,   4) \
X(a, STATIC,   SINGULAR, UINT32,   ranging_timeout_count,   5) \
X(a, STATIC,   SINGULAR, UINT32,   last_ranging_time_ms,   6) \
X(a, STATIC,   SINGULAR, FLOAT,    last_rms_error_m,   7) \
X(a, STATIC,   SINGULAR, INT32,    last_avg_rssi_dbm,   8) \
X(a, STATIC,   SINGULAR, UINT32,   last_update_timestamp_ms,   9)
#define protobuf_ranging_status_resp_t_CALLBACK NULL
#define protobuf_ranging_status_resp_t_DEFAULT NULL

#define protobuf_fota_state_resp_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    state,             1)
#define protobuf_fota_state_resp_t_CALLBACK NULL
#define protobuf_fota_state_resp_t_DEFAULT NULL

#define protobuf_battery_info_resp_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   bat_voltage_mv,    1) \
X(a, STATIC,   SINGULAR, UINT32,   bat_soc_percent,   2) \
X(a, STATIC,   SINGULAR, INT32,    remaining_min,     3) \
X(a, STATIC,   SINGULAR, BOOL,     is_charging,       4)
#define protobuf_battery_info_resp_t_CALLBACK NULL
#define protobuf_battery_info_resp_t_DEFAULT NULL

#define protobuf_battery_info_get_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define protobuf_battery_info_get_t_CALLBACK NULL
#define protobuf_battery_info_get_t_DEFAULT NULL

#define protobuf_packet_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  hdr,               1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,none,params.none),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,ack,params.ack),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,device_information_get,params.device_information_get),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,device_information_resp,params.device_information_resp),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,time_sync_get,params.time_sync_get),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,time_sync_set,params.time_sync_set),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,time_sync_resp,params.time_sync_resp),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,time_sync_adv_set,params.time_sync_adv_set),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,sys_config_get,params.sys_config_get),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,sys_config_set,params.sys_config_set),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,sys_config_resp,params.sys_config_resp),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,sys_ranging_cfg_get,params.sys_ranging_cfg_get),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,sys_ranging_cfg_set,params.sys_ranging_cfg_set),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,sys_ranging_cfg_resp,params.sys_ranging_cfg_resp),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,ranging_start,params.ranging_start),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,ranging_stop,params.ranging_stop),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,ranging_result,params.ranging_result),  18) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,ranging_status_get,params.ranging_status_get),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,ranging_status_resp,params.ranging_status_resp),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,filter_cfg_get,params.filter_cfg_get),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,filter_cfg_set,params.filter_cfg_set),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,filter_cfg_resp,params.filter_cfg_resp),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,device_reset,params.device_reset),  24) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,uwb_reset,params.uwb_reset),  25) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,factory_config_reset,params.factory_config_reset),  26) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,device_type_set,params.device_type_set),  27) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,device_type_get,params.device_type_get),  28) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,flash_erase,params.flash_erase),  29) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,flash_read,params.flash_read),  30) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,flash_data,params.flash_data),  31) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,flash_write,params.flash_write),  32) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,ble_adv_config_set,params.ble_adv_config_set),  33) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,ble_status_get,params.ble_status_get),  34) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,ble_status_resp,params.ble_status_resp),  35) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,ble_adv_status,params.ble_adv_status),  36) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,log_data,params.log_data),  37) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,log_clear,params.log_clear),  38) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,host_transport_set,params.host_transport_set),  39) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,pos_calib_cfg_get,params.pos_calib_cfg_get),  40) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,pos_calib_cfg_set,params.pos_calib_cfg_set),  41) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,pos_calib_cfg_resp,params.pos_calib_cfg_resp),  42) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,anchor_layout_get,params.anchor_layout_get),  43) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,anchor_layout_set,params.anchor_layout_set),  44) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,anchor_layout_resp,params.anchor_layout_resp),  45) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,flash_verify,params.flash_verify),  46) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,ble_conn_params_get,params.ble_conn_params_get),  47) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,ble_conn_params_set,params.ble_conn_params_set),  48) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,ble_conn_params_resp,params.ble_conn_params_resp),  49) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,ble_disconnect,params.ble_disconnect),  50) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,ble_scan_start,params.ble_scan_start),  51) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,ble_scan_stop,params.ble_scan_stop),  52) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,ble_connect,params.ble_connect),  53) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,ble_scan_result,params.ble_scan_result),  54) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,anchor_distance,params.anchor_distance),  55) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,tag_position,params.tag_position),  56) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,fota_state_resp,params.fota_state_resp),  57) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,battery_info_resp,params.battery_info_resp),  60) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,battery_info_get,params.battery_info_get),  61) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,enter_to_bootloader,params.enter_to_bootloader),  62)
#define protobuf_packet_t_CALLBACK NULL
#define protobuf_packet_t_DEFAULT NULL
#define protobuf_packet_t_hdr_MSGTYPE protobuf_hdr_t
#define protobuf_packet_t_params_none_MSGTYPE protobuf_none_t
#define protobuf_packet_t_params_ack_MSGTYPE protobuf_ack_t
#define protobuf_packet_t_params_device_information_get_MSGTYPE protobuf_device_information_get_t
#define protobuf_packet_t_params_device_information_resp_MSGTYPE protobuf_device_information_resp_t
#define protobuf_packet_t_params_time_sync_get_MSGTYPE protobuf_time_sync_get_t
#define protobuf_packet_t_params_time_sync_set_MSGTYPE protobuf_time_sync_set_t
#define protobuf_packet_t_params_time_sync_resp_MSGTYPE protobuf_time_sync_resp_t
#define protobuf_packet_t_params_time_sync_adv_set_MSGTYPE protobuf_time_sync_adv_set_t
#define protobuf_packet_t_params_sys_config_get_MSGTYPE protobuf_sys_config_get_t
#define protobuf_packet_t_params_sys_config_set_MSGTYPE protobuf_sys_config_set_t
#define protobuf_packet_t_params_sys_config_resp_MSGTYPE protobuf_sys_config_resp_t
#define protobuf_packet_t_params_sys_ranging_cfg_get_MSGTYPE protobuf_sys_ranging_cfg_get_t
#define protobuf_packet_t_params_sys_ranging_cfg_set_MSGTYPE protobuf_sys_ranging_cfg_set_t
#define protobuf_packet_t_params_sys_ranging_cfg_resp_MSGTYPE protobuf_sys_ranging_cfg_resp_t
#define protobuf_packet_t_params_ranging_start_MSGTYPE protobuf_ranging_start_t
#define protobuf_packet_t_params_ranging_stop_MSGTYPE protobuf_ranging_stop_t
#define protobuf_packet_t_params_ranging_result_MSGTYPE protobuf_ranging_result_t
#define protobuf_packet_t_params_ranging_status_get_MSGTYPE protobuf_ranging_status_get_t
#define protobuf_packet_t_params_ranging_status_resp_MSGTYPE protobuf_ranging_status_resp_t
#define protobuf_packet_t_params_filter_cfg_get_MSGTYPE protobuf_filter_cfg_get_t
#define protobuf_packet_t_params_filter_cfg_set_MSGTYPE protobuf_filter_cfg_set_t
#define protobuf_packet_t_params_filter_cfg_resp_MSGTYPE protobuf_filter_cfg_resp_t
#define protobuf_packet_t_params_device_reset_MSGTYPE protobuf_device_reset_t
#define protobuf_packet_t_params_uwb_reset_MSGTYPE protobuf_uwb_reset_t
#define protobuf_packet_t_params_factory_config_reset_MSGTYPE protobuf_factory_config_reset_t
#define protobuf_packet_t_params_device_type_set_MSGTYPE protobuf_device_type_set_t
#define protobuf_packet_t_params_device_type_get_MSGTYPE protobuf_device_type_get_t
#define protobuf_packet_t_params_flash_erase_MSGTYPE protobuf_flash_erase_t
#define protobuf_packet_t_params_flash_read_MSGTYPE protobuf_flash_read_t
#define protobuf_packet_t_params_flash_data_MSGTYPE protobuf_flash_data_t
#define protobuf_packet_t_params_flash_write_MSGTYPE protobuf_flash_write_t
#define protobuf_packet_t_params_ble_adv_config_set_MSGTYPE protobuf_ble_adv_config_t
#define protobuf_packet_t_params_ble_status_get_MSGTYPE protobuf_ble_status_get_t
#define protobuf_packet_t_params_ble_status_resp_MSGTYPE protobuf_ble_status_resp_t
#define protobuf_packet_t_params_ble_adv_status_MSGTYPE protobuf_ble_adv_status_t
#define protobuf_packet_t_params_log_data_MSGTYPE protobuf_log_data_t
#define protobuf_packet_t_params_log_clear_MSGTYPE protobuf_log_clear_t
#define protobuf_packet_t_params_host_transport_set_MSGTYPE protobuf_host_transport_set_t
#define protobuf_packet_t_params_pos_calib_cfg_get_MSGTYPE protobuf_pos_calib_cfg_get_t
#define protobuf_packet_t_params_pos_calib_cfg_set_MSGTYPE protobuf_pos_calib_cfg_set_t
#define protobuf_packet_t_params_pos_calib_cfg_resp_MSGTYPE protobuf_pos_calib_cfg_resp_t
#define protobuf_packet_t_params_anchor_layout_get_MSGTYPE protobuf_anchor_layout_get_t
#define protobuf_packet_t_params_anchor_layout_set_MSGTYPE protobuf_anchor_layout_set_t
#define protobuf_packet_t_params_anchor_layout_resp_MSGTYPE protobuf_anchor_layout_resp_t
#define protobuf_packet_t_params_flash_verify_MSGTYPE protobuf_flash_verify_t
#define protobuf_packet_t_params_ble_conn_params_get_MSGTYPE protobuf_ble_conn_params_get_t
#define protobuf_packet_t_params_ble_conn_params_set_MSGTYPE protobuf_ble_conn_params_set_t
#define protobuf_packet_t_params_ble_conn_params_resp_MSGTYPE protobuf_ble_conn_params_resp_t
#define protobuf_packet_t_params_ble_disconnect_MSGTYPE protobuf_ble_disconnect_t
#define protobuf_packet_t_params_ble_scan_start_MSGTYPE protobuf_ble_scan_start_t
#define protobuf_packet_t_params_ble_scan_stop_MSGTYPE protobuf_ble_scan_stop_t
#define protobuf_packet_t_params_ble_connect_MSGTYPE protobuf_ble_connect_t
#define protobuf_packet_t_params_ble_scan_result_MSGTYPE protobuf_ble_scan_result_t
#define protobuf_packet_t_params_anchor_distance_MSGTYPE protobuf_anchor_distance_t
#define protobuf_packet_t_params_tag_position_MSGTYPE protobuf_tag_position_t
#define protobuf_packet_t_params_fota_state_resp_MSGTYPE protobuf_fota_state_resp_t
#define protobuf_packet_t_params_battery_info_resp_MSGTYPE protobuf_battery_info_resp_t
#define protobuf_packet_t_params_battery_info_get_MSGTYPE protobuf_battery_info_get_t
#define protobuf_packet_t_params_enter_to_bootloader_MSGTYPE protobuf_enter_to_bootloader_t

extern const pb_msgdesc_t protobuf_addr_t_msg;
extern const pb_msgdesc_t protobuf_hdr_t_msg;
extern const pb_msgdesc_t protobuf_version_t_msg;
extern const pb_msgdesc_t protobuf_none_t_msg;
extern const pb_msgdesc_t protobuf_ack_t_msg;
extern const pb_msgdesc_t protobuf_device_information_get_t_msg;
extern const pb_msgdesc_t protobuf_device_information_resp_t_msg;
extern const pb_msgdesc_t protobuf_time_sync_get_t_msg;
extern const pb_msgdesc_t protobuf_time_sync_set_t_msg;
extern const pb_msgdesc_t protobuf_time_sync_resp_t_msg;
extern const pb_msgdesc_t protobuf_time_sync_adv_set_t_msg;
extern const pb_msgdesc_t protobuf_uwb_cfg_t_msg;
extern const pb_msgdesc_t protobuf_sys_config_get_t_msg;
extern const pb_msgdesc_t protobuf_sys_config_set_t_msg;
extern const pb_msgdesc_t protobuf_sys_config_resp_t_msg;
extern const pb_msgdesc_t protobuf_sys_ranging_cfg_t_msg;
extern const pb_msgdesc_t protobuf_sys_ranging_cfg_get_t_msg;
extern const pb_msgdesc_t protobuf_sys_ranging_cfg_set_t_msg;
extern const pb_msgdesc_t protobuf_sys_ranging_cfg_resp_t_msg;
extern const pb_msgdesc_t protobuf_ranging_start_t_msg;
extern const pb_msgdesc_t protobuf_ranging_stop_t_msg;
extern const pb_msgdesc_t protobuf_anchor_ranging_t_msg;
extern const pb_msgdesc_t protobuf_ranging_result_t_msg;
extern const pb_msgdesc_t protobuf_filter_cfg_t_msg;
extern const pb_msgdesc_t protobuf_filter_cfg_get_t_msg;
extern const pb_msgdesc_t protobuf_filter_cfg_set_t_msg;
extern const pb_msgdesc_t protobuf_filter_cfg_resp_t_msg;
extern const pb_msgdesc_t protobuf_device_reset_t_msg;
extern const pb_msgdesc_t protobuf_uwb_reset_t_msg;
extern const pb_msgdesc_t protobuf_factory_config_reset_t_msg;
extern const pb_msgdesc_t protobuf_enter_to_bootloader_t_msg;
extern const pb_msgdesc_t protobuf_device_type_set_t_msg;
extern const pb_msgdesc_t protobuf_device_type_get_t_msg;
extern const pb_msgdesc_t protobuf_flash_erase_t_msg;
extern const pb_msgdesc_t protobuf_flash_read_t_msg;
extern const pb_msgdesc_t protobuf_flash_data_t_msg;
extern const pb_msgdesc_t protobuf_flash_write_t_msg;
extern const pb_msgdesc_t protobuf_flash_verify_t_msg;
extern const pb_msgdesc_t protobuf_ble_adv_config_t_msg;
extern const pb_msgdesc_t protobuf_ble_status_get_t_msg;
extern const pb_msgdesc_t protobuf_ble_status_resp_t_msg;
extern const pb_msgdesc_t protobuf_ble_scan_result_t_msg;
extern const pb_msgdesc_t protobuf_ble_conn_params_t_msg;
extern const pb_msgdesc_t protobuf_ble_conn_params_get_t_msg;
extern const pb_msgdesc_t protobuf_ble_conn_params_set_t_msg;
extern const pb_msgdesc_t protobuf_ble_conn_params_resp_t_msg;
extern const pb_msgdesc_t protobuf_ble_disconnect_t_msg;
extern const pb_msgdesc_t protobuf_ble_scan_start_t_msg;
extern const pb_msgdesc_t protobuf_ble_scan_stop_t_msg;
extern const pb_msgdesc_t protobuf_ble_connect_t_msg;
extern const pb_msgdesc_t protobuf_ble_adv_status_t_msg;
extern const pb_msgdesc_t protobuf_anchor_distance_t_msg;
extern const pb_msgdesc_t protobuf_tag_position_t_msg;
extern const pb_msgdesc_t protobuf_log_data_t_msg;
extern const pb_msgdesc_t protobuf_log_clear_t_msg;
extern const pb_msgdesc_t protobuf_host_transport_set_t_msg;
extern const pb_msgdesc_t protobuf_pos_calib_cfg_t_msg;
extern const pb_msgdesc_t protobuf_pos_calib_cfg_get_t_msg;
extern const pb_msgdesc_t protobuf_pos_calib_cfg_set_t_msg;
extern const pb_msgdesc_t protobuf_pos_calib_cfg_resp_t_msg;
extern const pb_msgdesc_t protobuf_anchor_layout_item_t_msg;
extern const pb_msgdesc_t protobuf_anchor_layout_get_t_msg;
extern const pb_msgdesc_t protobuf_anchor_layout_set_t_msg;
extern const pb_msgdesc_t protobuf_anchor_layout_resp_t_msg;
extern const pb_msgdesc_t protobuf_ranging_status_get_t_msg;
extern const pb_msgdesc_t protobuf_ranging_status_resp_t_msg;
extern const pb_msgdesc_t protobuf_fota_state_resp_t_msg;
extern const pb_msgdesc_t protobuf_battery_info_resp_t_msg;
extern const pb_msgdesc_t protobuf_battery_info_get_t_msg;
extern const pb_msgdesc_t protobuf_packet_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define protobuf_addr_t_fields &protobuf_addr_t_msg
#define protobuf_hdr_t_fields &protobuf_hdr_t_msg
#define protobuf_version_t_fields &protobuf_version_t_msg
#define protobuf_none_t_fields &protobuf_none_t_msg
#define protobuf_ack_t_fields &protobuf_ack_t_msg
#define protobuf_device_information_get_t_fields &protobuf_device_information_get_t_msg
#define protobuf_device_information_resp_t_fields &protobuf_device_information_resp_t_msg
#define protobuf_time_sync_get_t_fields &protobuf_time_sync_get_t_msg
#define protobuf_time_sync_set_t_fields &protobuf_time_sync_set_t_msg
#define protobuf_time_sync_resp_t_fields &protobuf_time_sync_resp_t_msg
#define protobuf_time_sync_adv_set_t_fields &protobuf_time_sync_adv_set_t_msg
#define protobuf_uwb_cfg_t_fields &protobuf_uwb_cfg_t_msg
#define protobuf_sys_config_get_t_fields &protobuf_sys_config_get_t_msg
#define protobuf_sys_config_set_t_fields &protobuf_sys_config_set_t_msg
#define protobuf_sys_config_resp_t_fields &protobuf_sys_config_resp_t_msg
#define protobuf_sys_ranging_cfg_t_fields &protobuf_sys_ranging_cfg_t_msg
#define protobuf_sys_ranging_cfg_get_t_fields &protobuf_sys_ranging_cfg_get_t_msg
#define protobuf_sys_ranging_cfg_set_t_fields &protobuf_sys_ranging_cfg_set_t_msg
#define protobuf_sys_ranging_cfg_resp_t_fields &protobuf_sys_ranging_cfg_resp_t_msg
#define protobuf_ranging_start_t_fields &protobuf_ranging_start_t_msg
#define protobuf_ranging_stop_t_fields &protobuf_ranging_stop_t_msg
#define protobuf_anchor_ranging_t_fields &protobuf_anchor_ranging_t_msg
#define protobuf_ranging_result_t_fields &protobuf_ranging_result_t_msg
#define protobuf_filter_cfg_t_fields &protobuf_filter_cfg_t_msg
#define protobuf_filter_cfg_get_t_fields &protobuf_filter_cfg_get_t_msg
#define protobuf_filter_cfg_set_t_fields &protobuf_filter_cfg_set_t_msg
#define protobuf_filter_cfg_resp_t_fields &protobuf_filter_cfg_resp_t_msg
#define protobuf_device_reset_t_fields &protobuf_device_reset_t_msg
#define protobuf_uwb_reset_t_fields &protobuf_uwb_reset_t_msg
#define protobuf_factory_config_reset_t_fields &protobuf_factory_config_reset_t_msg
#define protobuf_enter_to_bootloader_t_fields &protobuf_enter_to_bootloader_t_msg
#define protobuf_device_type_set_t_fields &protobuf_device_type_set_t_msg
#define protobuf_device_type_get_t_fields &protobuf_device_type_get_t_msg
#define protobuf_flash_erase_t_fields &protobuf_flash_erase_t_msg
#define protobuf_flash_read_t_fields &protobuf_flash_read_t_msg
#define protobuf_flash_data_t_fields &protobuf_flash_data_t_msg
#define protobuf_flash_write_t_fields &protobuf_flash_write_t_msg
#define protobuf_flash_verify_t_fields &protobuf_flash_verify_t_msg
#define protobuf_ble_adv_config_t_fields &protobuf_ble_adv_config_t_msg
#define protobuf_ble_status_get_t_fields &protobuf_ble_status_get_t_msg
#define protobuf_ble_status_resp_t_fields &protobuf_ble_status_resp_t_msg
#define protobuf_ble_scan_result_t_fields &protobuf_ble_scan_result_t_msg
#define protobuf_ble_conn_params_t_fields &protobuf_ble_conn_params_t_msg
#define protobuf_ble_conn_params_get_t_fields &protobuf_ble_conn_params_get_t_msg
#define protobuf_ble_conn_params_set_t_fields &protobuf_ble_conn_params_set_t_msg
#define protobuf_ble_conn_params_resp_t_fields &protobuf_ble_conn_params_resp_t_msg
#define protobuf_ble_disconnect_t_fields &protobuf_ble_disconnect_t_msg
#define protobuf_ble_scan_start_t_fields &protobuf_ble_scan_start_t_msg
#define protobuf_ble_scan_stop_t_fields &protobuf_ble_scan_stop_t_msg
#define protobuf_ble_connect_t_fields &protobuf_ble_connect_t_msg
#define protobuf_ble_adv_status_t_fields &protobuf_ble_adv_status_t_msg
#define protobuf_anchor_distance_t_fields &protobuf_anchor_distance_t_msg
#define protobuf_tag_position_t_fields &protobuf_tag_position_t_msg
#define protobuf_log_data_t_fields &protobuf_log_data_t_msg
#define protobuf_log_clear_t_fields &protobuf_log_clear_t_msg
#define protobuf_host_transport_set_t_fields &protobuf_host_transport_set_t_msg
#define protobuf_pos_calib_cfg_t_fields &protobuf_pos_calib_cfg_t_msg
#define protobuf_pos_calib_cfg_get_t_fields &protobuf_pos_calib_cfg_get_t_msg
#define protobuf_pos_calib_cfg_set_t_fields &protobuf_pos_calib_cfg_set_t_msg
#define protobuf_pos_calib_cfg_resp_t_fields &protobuf_pos_calib_cfg_resp_t_msg
#define protobuf_anchor_layout_item_t_fields &protobuf_anchor_layout_item_t_msg
#define protobuf_anchor_layout_get_t_fields &protobuf_anchor_layout_get_t_msg
#define protobuf_anchor_layout_set_t_fields &protobuf_anchor_layout_set_t_msg
#define protobuf_anchor_layout_resp_t_fields &protobuf_anchor_layout_resp_t_msg
#define protobuf_ranging_status_get_t_fields &protobuf_ranging_status_get_t_msg
#define protobuf_ranging_status_resp_t_fields &protobuf_ranging_status_resp_t_msg
#define protobuf_fota_state_resp_t_fields &protobuf_fota_state_resp_t_msg
#define protobuf_battery_info_resp_t_fields &protobuf_battery_info_resp_t_msg
#define protobuf_battery_info_get_t_fields &protobuf_battery_info_get_t_msg
#define protobuf_packet_t_fields &protobuf_packet_t_msg

/* Maximum encoded size of messages (where known) */
#define PROTOBUF_PROTOCOL_PB_H_MAX_SIZE          protobuf_packet_t_size
#define protobuf_ack_t_size                      8
#define protobuf_addr_t_size                     4
#define protobuf_anchor_distance_t_size          23
#define protobuf_anchor_layout_get_t_size        6
#define protobuf_anchor_layout_item_t_size       21
#define protobuf_anchor_layout_resp_t_size       92
#define protobuf_anchor_layout_set_t_size        92
#define protobuf_anchor_ranging_t_size           23
#define protobuf_battery_info_get_t_size         6
#define protobuf_battery_info_resp_t_size        25
#define protobuf_ble_adv_config_t_size           41
#define protobuf_ble_adv_status_t_size           38
#define protobuf_ble_conn_params_get_t_size      6
#define protobuf_ble_conn_params_resp_t_size     26
#define protobuf_ble_conn_params_set_t_size      26
#define protobuf_ble_conn_params_t_size          24
#define protobuf_ble_connect_t_size              8
#define protobuf_ble_disconnect_t_size           6
#define protobuf_ble_scan_result_t_size          58
#define protobuf_ble_scan_start_t_size           20
#define protobuf_ble_scan_stop_t_size            6
#define protobuf_ble_status_get_t_size           6
#define protobuf_ble_status_resp_t_size          19
#define protobuf_device_information_get_t_size   6
#define protobuf_device_information_resp_t_size  67
#define protobuf_device_reset_t_size             6
#define protobuf_device_type_get_t_size          6
#define protobuf_device_type_set_t_size          2
#define protobuf_enter_to_bootloader_t_size      6
#define protobuf_factory_config_reset_t_size     6
#define protobuf_filter_cfg_get_t_size           6
#define protobuf_filter_cfg_resp_t_size          29
#define protobuf_filter_cfg_set_t_size           29
#define protobuf_filter_cfg_t_size               27
#define protobuf_flash_data_t_size               203
#define protobuf_flash_erase_t_size              8
#define protobuf_flash_read_t_size               12
#define protobuf_flash_verify_t_size             6
#define protobuf_flash_write_t_size              209
#define protobuf_fota_state_resp_t_size          2
#define protobuf_hdr_t_size                      18
#define protobuf_host_transport_set_t_size       2
#define protobuf_log_clear_t_size                14
#define protobuf_log_data_t_size                 197
#define protobuf_none_t_size                     6
#define protobuf_packet_t_size                   233
#define protobuf_pos_calib_cfg_get_t_size        6
#define protobuf_pos_calib_cfg_resp_t_size       55
#define protobuf_pos_calib_cfg_set_t_size        55
#define protobuf_pos_calib_cfg_t_size            53
#define protobuf_ranging_result_t_size           141
#define protobuf_ranging_start_t_size            2
#define protobuf_ranging_status_get_t_size       6
#define protobuf_ranging_status_resp_t_size      58
#define protobuf_ranging_stop_t_size             6
#define protobuf_sys_config_get_t_size           6
#define protobuf_sys_config_resp_t_size          74
#define protobuf_sys_config_set_t_size           74
#define protobuf_sys_ranging_cfg_get_t_size      6
#define protobuf_sys_ranging_cfg_resp_t_size     14
#define protobuf_sys_ranging_cfg_set_t_size      14
#define protobuf_sys_ranging_cfg_t_size          12
#define protobuf_tag_position_t_size             26
#define protobuf_time_sync_adv_set_t_size        30
#define protobuf_time_sync_get_t_size            6
#define protobuf_time_sync_resp_t_size           22
#define protobuf_time_sync_set_t_size            22
#define protobuf_uwb_cfg_t_size                  72
#define protobuf_uwb_reset_t_size                6
#define protobuf_version_t_size                  35

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
