/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "protocol.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(protobuf_addr_t, protobuf_addr_t, AUTO)


PB_BIND(protobuf_hdr_t, protobuf_hdr_t, AUTO)


PB_BIND(protobuf_version_t, protobuf_version_t, AUTO)


PB_BIND(protobuf_none_t, protobuf_none_t, AUTO)


PB_BIND(protobuf_ack_t, protobuf_ack_t, AUTO)


PB_BIND(protobuf_device_information_get_t, protobuf_device_information_get_t, AUTO)


PB_BIND(protobuf_device_information_resp_t, protobuf_device_information_resp_t, AUTO)


PB_BIND(protobuf_time_sync_get_t, protobuf_time_sync_get_t, AUTO)


PB_BIND(protobuf_time_sync_set_t, protobuf_time_sync_set_t, AUTO)


PB_BIND(protobuf_time_sync_resp_t, protobuf_time_sync_resp_t, AUTO)


PB_BIND(protobuf_time_sync_adv_set_t, protobuf_time_sync_adv_set_t, AUTO)


PB_BIND(protobuf_uwb_cfg_t, protobuf_uwb_cfg_t, AUTO)


PB_BIND(protobuf_sys_config_get_t, protobuf_sys_config_get_t, AUTO)


PB_BIND(protobuf_sys_config_set_t, protobuf_sys_config_set_t, AUTO)


PB_BIND(protobuf_sys_config_resp_t, protobuf_sys_config_resp_t, AUTO)


PB_BIND(protobuf_sys_ranging_cfg_t, protobuf_sys_ranging_cfg_t, AUTO)


PB_BIND(protobuf_sys_ranging_cfg_get_t, protobuf_sys_ranging_cfg_get_t, AUTO)


PB_BIND(protobuf_sys_ranging_cfg_set_t, protobuf_sys_ranging_cfg_set_t, AUTO)


PB_BIND(protobuf_sys_ranging_cfg_resp_t, protobuf_sys_ranging_cfg_resp_t, AUTO)


PB_BIND(protobuf_ranging_start_t, protobuf_ranging_start_t, AUTO)


PB_BIND(protobuf_ranging_stop_t, protobuf_ranging_stop_t, AUTO)


PB_BIND(protobuf_anchor_ranging_t, protobuf_anchor_ranging_t, AUTO)


PB_BIND(protobuf_ranging_result_t, protobuf_ranging_result_t, AUTO)


PB_BIND(protobuf_sensor_fusion_cfg_t, protobuf_sensor_fusion_cfg_t, AUTO)


PB_BIND(protobuf_sensor_fusion_cfg_get_t, protobuf_sensor_fusion_cfg_get_t, AUTO)


PB_BIND(protobuf_sensor_fusion_cfg_set_t, protobuf_sensor_fusion_cfg_set_t, AUTO)


PB_BIND(protobuf_sensor_fusion_cfg_resp_t, protobuf_sensor_fusion_cfg_resp_t, AUTO)


PB_BIND(protobuf_device_reset_t, protobuf_device_reset_t, AUTO)


PB_BIND(protobuf_uwb_reset_t, protobuf_uwb_reset_t, AUTO)


PB_BIND(protobuf_factory_config_reset_t, protobuf_factory_config_reset_t, AUTO)


PB_BIND(protobuf_enter_to_bootloader_t, protobuf_enter_to_bootloader_t, AUTO)


PB_BIND(protobuf_device_type_set_t, protobuf_device_type_set_t, AUTO)


PB_BIND(protobuf_device_type_get_t, protobuf_device_type_get_t, AUTO)


PB_BIND(protobuf_flash_erase_t, protobuf_flash_erase_t, AUTO)


PB_BIND(protobuf_flash_read_t, protobuf_flash_read_t, AUTO)


PB_BIND(protobuf_flash_data_t, protobuf_flash_data_t, AUTO)


PB_BIND(protobuf_flash_write_t, protobuf_flash_write_t, AUTO)


PB_BIND(protobuf_flash_verify_t, protobuf_flash_verify_t, AUTO)


PB_BIND(protobuf_ble_adv_config_t, protobuf_ble_adv_config_t, AUTO)


PB_BIND(protobuf_ble_status_get_t, protobuf_ble_status_get_t, AUTO)


PB_BIND(protobuf_ble_status_resp_t, protobuf_ble_status_resp_t, AUTO)


PB_BIND(protobuf_ble_scan_result_t, protobuf_ble_scan_result_t, AUTO)


PB_BIND(protobuf_ble_conn_params_t, protobuf_ble_conn_params_t, AUTO)


PB_BIND(protobuf_ble_conn_params_get_t, protobuf_ble_conn_params_get_t, AUTO)


PB_BIND(protobuf_ble_conn_params_set_t, protobuf_ble_conn_params_set_t, AUTO)


PB_BIND(protobuf_ble_conn_params_resp_t, protobuf_ble_conn_params_resp_t, AUTO)


PB_BIND(protobuf_ble_disconnect_t, protobuf_ble_disconnect_t, AUTO)


PB_BIND(protobuf_ble_scan_start_t, protobuf_ble_scan_start_t, AUTO)


PB_BIND(protobuf_ble_scan_stop_t, protobuf_ble_scan_stop_t, AUTO)


PB_BIND(protobuf_ble_connect_t, protobuf_ble_connect_t, AUTO)


PB_BIND(protobuf_ble_adv_status_t, protobuf_ble_adv_status_t, AUTO)


PB_BIND(protobuf_anchor_distance_t, protobuf_anchor_distance_t, AUTO)


PB_BIND(protobuf_tag_position_t, protobuf_tag_position_t, AUTO)


PB_BIND(protobuf_log_data_t, protobuf_log_data_t, AUTO)


PB_BIND(protobuf_log_clear_t, protobuf_log_clear_t, AUTO)


PB_BIND(protobuf_host_transport_set_t, protobuf_host_transport_set_t, AUTO)


PB_BIND(protobuf_pos_calib_cfg_t, protobuf_pos_calib_cfg_t, AUTO)


PB_BIND(protobuf_pos_calib_cfg_get_t, protobuf_pos_calib_cfg_get_t, AUTO)


PB_BIND(protobuf_pos_calib_cfg_set_t, protobuf_pos_calib_cfg_set_t, AUTO)


PB_BIND(protobuf_pos_calib_cfg_resp_t, protobuf_pos_calib_cfg_resp_t, AUTO)


PB_BIND(protobuf_anchor_layout_item_t, protobuf_anchor_layout_item_t, AUTO)


PB_BIND(protobuf_anchor_layout_get_t, protobuf_anchor_layout_get_t, AUTO)


PB_BIND(protobuf_anchor_layout_set_t, protobuf_anchor_layout_set_t, AUTO)


PB_BIND(protobuf_anchor_layout_resp_t, protobuf_anchor_layout_resp_t, AUTO)


PB_BIND(protobuf_ranging_status_get_t, protobuf_ranging_status_get_t, AUTO)


PB_BIND(protobuf_ranging_status_resp_t, protobuf_ranging_status_resp_t, AUTO)


PB_BIND(protobuf_fota_state_resp_t, protobuf_fota_state_resp_t, AUTO)


PB_BIND(protobuf_battery_info_resp_t, protobuf_battery_info_resp_t, AUTO)


PB_BIND(protobuf_battery_info_get_t, protobuf_battery_info_get_t, AUTO)


PB_BIND(protobuf_end_session_t, protobuf_end_session_t, AUTO)


PB_BIND(protobuf_packet_t, protobuf_packet_t, AUTO)































