M48
; DRILL file {KiCad 9.0.7} date 2026-05-06T22:58:20+0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-06T22:58:20+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X36.133Y-76.61
X36.133Y-82.39
T2
X53.625Y-100.09
X57.875Y-100.09
T3
X33.5Y-52.6
X33.5Y-99.6
X78.5Y-52.6
X78.5Y-99.6
M30
